In [1]:
import os
print(os.getcwd())
os.chdir('/home/fatemeh/thesis/kinodata-3D-affinity-prediction')
print(os.getcwd())

/home/fatemeh/thesis/kinodata-3D-affinity-prediction/examples
/home/fatemeh/thesis/kinodata-3D-affinity-prediction

In [2]:
# import kinodata-3d-affinity-prediction
import kinodata
from kinodata.data import KinodataDocked
from kinodata.transform import TransformToComplexGraph
from kinodata.types import *


import json
from pathlib import Path
from typing import Any
from functools import partial

import torch
from torch_geometric.loader import DataLoader

import kinodata.configuration as cfg
# from kinodata.model import ComplexTransformer, DTIModel, RegressionModel
from kinodata.model import ComplexTransformer, RegressionModel
from kinodata.model.complex_transformer import make_model as make_complex_transformer
# from kinodata.model.dti import make_model as make_dti_baseline
from kinodata.data.data_module import make_kinodata_module
from kinodata.transform import TransformToComplexGraph

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import tqdm


!wandb disabled

W&B disabled.

## Whole Data
Saving a portion

In [3]:
data = KinodataDocked(transform=TransformToComplexGraph(remove_heterogeneous_representation=False))

In [ ]:
mini_data = data[:100]
mini_data
torch.save(mini_data, "data/probing/100subset_data.pt")

NameError: name 'data' is not defined

In [14]:
a_complex = mini_data[0]
torch.save(a_complex, "data/probing/a_complex.pt")

In [12]:
with open("data/probing/ident_to_idx.json", "w") as f:
    json.dump(mini_data.ident_index_map(), f)

### Looking at data

In [4]:
# print(data)
# print(dir(data))
print(data.__dict__)
# print(data[0])

{'remove_hydrogen': True, '_prefix': None, 'residue_representation': 'sequence', 'require_kissim_residues': False, 'use_multiprocessing': True, 'make_pyg_data': functools.partial(<function process_pyg at 0x7fed1d478a40>, residue_representation='sequence', require_kissim_residues=False), 'num_processes': 16, 'post_filter': None, 'root': '/home/fatemeh/thesis/kinodata-3D-affinity-prediction/data', 'transform': TransformToComplexGraph(), 'pre_transform': None, 'pre_filter': FilterActivityType(allowed=pIC50), 'log': True, '_indices': None, 'force_reload': False, '_data': HeteroData(
  y=[41238],
  docking_score=[41238],
  posit_prob=[41238],
  predicted_rmsd=[41238],
  pocket_sequence=[41238],
  scaffold=[41238],
  activity_type=[41238],
  ident=[41238],
  smiles=[41238],
  ligand={
    z=[1288419],
    x=[1288419, 12],
    pos=[1288419, 3],
  },
  pocket={
    z=[27393111],
    x=[27393111, 12],
    pos=[27393111, 3],
  },
  pocket_residue={ x=[3498751, 23] },
  (ligand, bond, ligand)={
    edge_index=[2, 2857602],
    edge_attr=[2857602, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 55219856],
    edge_attr=[55219856, 4],
  }
), 'slices': defaultdict(<class 'dict'>, {'y': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'docking_score': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'posit_prob': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'predicted_rmsd': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'pocket_sequence': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'scaffold': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'activity_type': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'ident': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'smiles': tensor([    0,     1,     2,  ..., 41236, 41237, 41238]), 'ligand': {'z': tensor([      0,      24,      50,  ..., 1288338, 1288382, 1288419]), 'x': tensor([      0,      24,      50,  ..., 1288338, 1288382, 1288419]), 'pos': tensor([      0,      24,      50,  ..., 1288338, 1288382, 1288419])}, 'pocket': {'z': tensor([       0,      652,     1304,  ..., 27391863, 27392480, 27393111]), 'x': tensor([       0,      652,     1304,  ..., 27391863, 27392480, 27393111]), 'pos': tensor([       0,      652,     1304,  ..., 27391863, 27392480, 27393111])}, 'pocket_residue': {'x': tensor([      0,      85,     170,  ..., 3498581, 3498666, 3498751])}, ('ligand', 'bond', 'ligand'): {'edge_index': tensor([      0,      54,     112,  ..., 2857424, 2857520, 2857602]), 'edge_attr': tensor([      0,      54,     112,  ..., 2857424, 2857520, 2857602])}, ('pocket', 'bond', 'pocket'): {'edge_index': tensor([       0,     1308,     2616,  ..., 55217352, 55218588, 55219856]), 'edge_attr': tensor([       0,     1308,     2616,  ..., 55217352, 55218588, 55219856])}}), '_data_list': None}

In [ ]:
# print(data.{'pocket'})
# print(data.data.keys())
# print(data.data.edge_types)
# print(data.data.node_types)
# print(data[2].edge_attrs)
# print(data[2].node_attrs)
# print(data[2].edge_stores)
print(data[2])

['posit_prob', 'pos', 'scaffold', 'ident', 'y', 'edge_attr', 'pocket_sequence', 'activity_type', 'edge_index', 'docking_score', 'predicted_rmsd', 'z', 'x', 'smiles']

In [ ]:
data.data

/home/fatemeh/miniconda3/envs/kinodata3d/lib/python3.12/site-packages/torch_geometric/data/in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. The data of the dataset is already cached, so any modifications to `data` will not be reflected when accessing its elements. Clearing the cache now by removing all elements in `dataset._data_list`. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)

HeteroData(
  y=[41238],
  docking_score=[41238],
  posit_prob=[41238],
  predicted_rmsd=[41238],
  pocket_sequence=[41238],
  scaffold=[41238],
  activity_type=[41238],
  ident=[41238],
  smiles=[41238],
  ligand={
    z=[1288419],
    x=[1288419, 12],
    pos=[1288419, 3],
  },
  pocket={
    z=[27393111],
    x=[27393111, 12],
    pos=[27393111, 3],
  },
  pocket_residue={ x=[3498751, 23] },
  (ligand, bond, ligand)={
    edge_index=[2, 2857602],
    edge_attr=[2857602, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 55219856],
    edge_attr=[55219856, 4],
  }
)

In [ ]:
sample = data[1]
node_types, edge_types = sample.metadata()
print(f"Node types: {', '.join([nt for nt in node_types])}")
print(f"Edge types: {', '.join([str(et) for et in edge_types])}")
print(f"Number of ligand heavy atoms: {sample['ligand'].x.size(0)}")
print(f"Number of pocket heavy atoms: {sample['pocket'].x.size(0)}")
print(f"Position of ligand atom indexed 0: {sample['ligand'].pos[0]}")
print(f"Position of pocket atom indexed 0: {sample['pocket'].pos[0]}")

Node types: ligand, pocket, pocket_residue
Edge types: ('ligand', 'bond', 'ligand'), ('pocket', 'bond', 'pocket')
Number of ligand heavy atoms: 26
Number of pocket heavy atoms: 652
Position of ligand atom indexed 0: tensor([ 5.4872, 25.3067, 37.4988])
Position of pocket atom indexed 0: tensor([ 9.5601, 17.7450, 49.1304])

In [ ]:
graf = TransformToComplexGraph()(sample)
graf

HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='C1CCC(CCC2CCC(CC3CCCCC3)C3CCCCC23)CC1',
  activity_type='pIC50',
  ident=[1],
  smiles='Clc1ccc(Nc2nnc(NCc3ccncc3)c3ccccc23)cc1',
  ligand={
    z=[26],
    x=[26, 12],
    pos=[26, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[678, 12],
    z=[678],
    pos=[678, 3],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 58],
    edge_attr=[58, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1366],
    edge_attr=[1366, 4],
  }
)

In [ ]:
import networkx as nx
from pyvis.network import Network

def interactive_hetero_graph(data):
    # Initialize PyVis network object with remote CDN resources to avoid permission issues
    net = Network(notebook=True, width="1000px", height="700px", directed=False, cdn_resources="remote")

    # Loop over each node type in HeteroData
    for node_type in data.node_types:
        node_indices = data[node_type].num_nodes
        for i in range(node_indices):
            node_id = f"{node_type}_{i}"
            # Color nodes differently based on their type
            color = 'blue' if node_type == 'protein' else 'green' if node_type == 'ligand' else 'gray'
            net.add_node(node_id, label=node_id, color=color)

    # Loop over each edge type in HeteroData
    for edge_type in data.edge_types:
        edge_index = data[edge_type].edge_index
        source_node_type, relation_type, target_node_type = edge_type

        # Adding edges to PyVis graph
        for i in range(edge_index.size(1)):  # edge_index is (2, num_edges)
            source = edge_index[0, i].item()
            target = edge_index[1, i].item()

            source_id = f"{source_node_type}_{source}"
            target_id = f"{target_node_type}_{target}"

            net.add_edge(source_id, target_id, label=relation_type)

    # Display the interactive graph
    return net.show("hetero_graph.html")

# Usage: assuming your HeteroData object is loaded as 'data'
interactive_hetero_graph(sample)

hetero_graph.html

# Match PyG data to the ChemEMBL activity_ids

In [4]:
_DATA = Path.cwd() / "data"
_DATA

PosixPath('/home/fatemeh/thesis/kinodata-3D-affinity-prediction/data')

In [9]:
from rdkit.Chem import PandasTools

raw_dir = _DATA / "raw"
file_name = "kinodata_docked_v2.sdf.gz",
raw_fp = f"{_DATA}/raw/kinodata_docked_v2.sdf.gz"

raw_data_df = PandasTools.LoadSDF(
    raw_fp,
    smilesName="compound_structures.canonical_smiles",
    molColName="molecule",
    embedProps=True,
    removeHs=True,
)

In [10]:
raw_data_df.head()

,assays.chembl_id,target_dictionary.chembl_id,molecule_dictionary.chembl_id,molecule_dictionary.max_phase,activities.standard_type,activities.standard_value,activities.standard_units,compound_structures.canonical_smiles,compound_structures.standard_inchi,component_sequences.sequence,...,docking.posit_probability,docking.duration,similar.klifs_structure_id,similar.ligand_pdb,similar.complex_pdb,similar.chain,similar.fp_similarity,docking.predicted_rmsd,ID,molecule
0,CHEMBL847682,CHEMBL4128,CHEMBL69638,0,pIC50,5.468521,nM,Nc1ncnc2c1c(-c1cccc(Oc3ccccc3)c1)cn2C1CCCC1,InChI=1S/C23H22N4O/c24-22-21-20(14-27(17-8-4-5...,MDSLASLVLCGVSLLLSGTVEGAMDLILINSLPLVSDAETSLTCIA...,...,0.24,62.318077,5553.0,QQ1,2WQB,A,0.298246,4.790116,32336,<rdkit.Chem.rdchem.Mol object at 0x7fd0526eb1b0>
1,CHEMBL674643,CHEMBL203,CHEMBL306988,0,pIC50,3.30103,nM,CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)[O-])cc1,InChI=1S/C15H13N3O3/c1-10(12(8-16)9-17)11-2-4-...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,...,0.05,83.548552,10374.0,FZP,6D8E,A,0.232877,6.358418,32770,<rdkit.Chem.rdchem.Mol object at 0x7fd0526eb140>
2,CHEMBL812621,CHEMBL279,CHEMBL419526,0,pIC50,5.725842,nM,c1ccc(-c2cnc(Nc3ccccn3)o2)cc1,InChI=1S/C14H11N3O/c1-2-6-11(7-3-1)12-10-16-14...,MQSKVLLAVALWLCVETRAASVGLPSVSLDLPRLSIQKDILTIKAN...,...,0.05,513.319727,7065.0,6NC,5JT2,A,0.142857,5.895421,33033,<rdkit.Chem.rdchem.Mol object at 0x7fd0526eb220>
3,CHEMBL664848,CHEMBL3142,CHEMBL104450,0,pIC50,6.455932,nM,O=c1cc(-c2cccc(-c3ccc(O)cc3)c2)sc(N2CCOCC2)c1,InChI=1S/C21H19NO3S/c23-18-6-4-15(5-7-18)16-2-...,MAGSGAGVRCSLLRLQETLSAADRCGAALAGHQLIRGLGQECVLSS...,...,0.18,71.917884,2316.0,07U,3TXO,A,0.163636,4.018659,33375,<rdkit.Chem.rdchem.Mol object at 0x7fd0526eb290>
4,CHEMBL812621,CHEMBL279,CHEMBL330621,0,pIC50,7.721246,nM,Cc1ccc(Nc2ncc(-c3ccccc3)s2)nc1,InChI=1S/C15H13N3S/c1-11-7-8-14(16-9-11)18-15-...,MQSKVLLAVALWLCVETRAASVGLPSVSLDLPRLSIQKDILTIKAN...,...,0.18,71.689741,5323.0,AAZ,1Y6A,A,0.4,4.664443,34276,<rdkit.Chem.rdchem.Mol object at 0x7fd0526eb300>

In [13]:
raw_data_df.columns

Index(['assays.chembl_id', 'target_dictionary.chembl_id',
       'molecule_dictionary.chembl_id', 'molecule_dictionary.max_phase',
       'activities.standard_type', 'activities.standard_value',
       'activities.standard_units', 'compound_structures.canonical_smiles',
       'compound_structures.standard_inchi', 'component_sequences.sequence',
       'assays.confidence_score', 'docs.chembl_id', 'docs.year',
       'docs.authors', 'UniprotID', 'docking.chemgauss_score',
       'docking.posit_probability', 'docking.duration',
       'similar.klifs_structure_id', 'similar.ligand_pdb',
       'similar.complex_pdb', 'similar.chain', 'similar.fp_similarity',
       'docking.predicted_rmsd', 'ID', 'molecule'],
      dtype='object')

Save a mapping of index to activity id (named as ID)

In [ ]:
ident_activityID_map = raw_data_df['ID'].to_dict()
with open("data/probing/ident_activityID_map.json", "w") as f:
    json.dump(ident_activityID_map, f)

In [ ]:
with open("data/probing/ident_activityID_map.json", "r") as f:
    ident_activityID_map = json.load(f)
ident_activityID_map

{'0': '32336',
 '1': '32770',
 '2': '33033',
 '3': '33375',
 '4': '34276',
 '5': '35297',
 '6': '35302',
 '7': '35519',
 '8': '36519',
 '9': '37861',
 '10': '39110',
 '11': '40257',
 '12': '40607',
 '13': '40689',
 '14': '40692',
 '15': '40693',
 '16': '40694',
 '17': '41222',
 '18': '41866',
 '19': '41979',
 '20': '41980',
 '21': '41983',
 '22': '41985',
 '23': '41986',
 '24': '41987',
 '25': '42683',
 '26': '42689',
 '27': '43147',
 '28': '44685',
 '29': '45078',
 '30': '45079',
 '31': '45962',
 '32': '46268',
 '33': '49408',
 '34': '49411',
 '35': '49413',
 '36': '50202',
 '37': '51439',
 '38': '51440',
 '39': '51883',
 '40': '51885',
 '41': '51886',
 '42': '51887',
 '43': '53296',
 '44': '53297',
 '45': '53762',
 '46': '53764',
 '47': '53967',
 '48': '53974',
 '49': '54991',
 '50': '55137',
 '51': '55138',
 '52': '57444',
 '53': '57679',
 '54': '58605',
 '55': '60020',
 '56': '60799',
 '57': '60800',
 '58': '60801',
 '59': '61302',
 '60': '62027',
 '61': '62143',
 '62': '62147',
 '63': '62149',
 '64': '62715',
 '65': '62721',
 '66': '64049',
 '67': '66108',
 '68': '66112',
 '69': '66113',
 '70': '66857',
 '71': '67197',
 '72': '67658',
 '73': '67823',
 '74': '69004',
 '75': '69112',
 '76': '69117',
 '77': '70767',
 '78': '71058',
 '79': '71734',
 '80': '72284',
 '81': '72612',
 '82': '72615',
 '83': '72620',
 '84': '74664',
 '85': '74688',
 '86': '74691',
 '87': '74694',
 '88': '75874',
 '89': '75878',
 '90': '76647',
 '91': '76966',
 '92': '78064',
 '93': '78067',
 '94': '81208',
 '95': '81210',
 '96': '81560',
 '97': '82616',
 '98': '82619',
 '99': '83585',
 '100': '84585',
 '101': '84588',
 '102': '85354',
 '103': '85671',
 '104': '86223',
 '105': '86274',
 '106': '86581',
 '107': '86584',
 '108': '87307',
 '109': '88332',
 '110': '88690',
 '111': '89581',
 '112': '89608',
 '113': '89611',
 '114': '89614',
 '115': '90223',
 '116': '90620',
 '117': '92272',
 '118': '92649',
 '119': '93279',
 '120': '94280',
 '121': '94578',
 '122': '94581',
 '123': '95252',
 '124': '95253',
 '125': '95565',
 '126': '96649',
 '127': '97344',
 '128': '97667',
 '129': '97670',
 '130': '98692',
 '131': '98695',
 '132': '99307',
 '133': '100544',
 '134': '101634',
 '135': '102362',
 '136': '102363',
 '137': '103601',
 '138': '103604',
 '139': '103607',
 '140': '104237',
 '141': '104238',
 '142': '105375',
 '143': '105520',
 '144': '105521',
 '145': '105524',
 '146': '105738',
 '147': '106511',
 '148': '106877',
 '149': '107292',
 '150': '107298',
 '151': '107300',
 '152': '107302',
 '153': '107304',
 '154': '107306',
 '155': '107703',
 '156': '107705',
 '157': '108038',
 '158': '108039',
 '159': '108285',
 '160': '108289',
 '161': '108795',
 '162': '108799',
 '163': '108863',
 '164': '108868',
 '165': '109637',
 '166': '110154',
 '167': '110155',
 '168': '110218',
 '169': '110219',
 '170': '110542',
 '171': '110543',
 '172': '111012',
 '173': '111014',
 '174': '111016',
 '175': '111164',
 '176': '111575',
 '177': '111577',
 '178': '111579',
 '179': '111581',
 '180': '111618',
 '181': '111702',
 '182': '112446',
 '183': '112450',
 '184': '112452',
 '185': '113043',
 '186': '113112',
 '187': '113113',
 '188': '113789',
 '189': '113791',
 '190': '113793',
 '191': '114278',
 '192': '114280',
 '193': '114282',
 '194': '114283',
 '195': '114286',
 '196': '114344',
 '197': '114352',
 '198': '114696',
 '199': '115003',
 '200': '115399',
 '201': '115583',
 '202': '115964',
 '203': '116836',
 '204': '116837',
 '205': '116878',
 '206': '116920',
 '207': '116921',
 '208': '116922',
 '209': '117213',
 '210': '117675',
 '211': '118041',
 '212': '118084',
 '213': '118168',
 '214': '118169',
 '215': '118171',
 '216': '118461',
 '217': '118470',
 '218': '118471',
 '219': '118833',
 '220': '119256',
 '221': '119373',
 '222': '119374',
 '223': '119377',
 '224': '119381',
 '225': '119382',
 '226': '119600',
 '227': '119601',
 '228': '120047',
 '229': '120054',
 '230': '120115',
 '231': '120506',
 '232': '120507',
 '233': '120871',
 '234': '121281',
 '235': '121338',
 '236': '121677',
 '237': '121680',
 '238': '121807',
 '239': '121808',
 '240': '121811',
 '241': '122503',
 '242': '122509',
 '243': '122511',
 '244': '122513',
 '245': '122558',
 '246': '122914',
 '247': '122965',
 '248': '123355',
 '249': '123749',
 '250': '124201',
 '251': '124664',
 '252': '124665',
 '253': '125063',
 '254': '125121',
 '255': '125499',
 '256': '125500',
 '257': '125512',
 '258': '125565',
 '259': '125813',
 '260': '126536',
 '261': '126999',
 '262': '127000',
 '263': '127175',
 '264': '127421',
 '265': '127736',
 '266': '127738',
 '267': '127740',
 '268': '128504',
 '269': '128845',
 '270': '128847',
 '271': '128961',
 '272': '129335',
 '273': '129336',
 '274': '129337',
 '275': '129340',
 '276': '129526',
 '277': '130154',
 '278': '130156',
 '279': '130729',
 '280': '130731',
 '281': '130744',
 '282': '130786',
 '283': '130787',
 '284': '130900',
 '285': '131160',
 '286': '131439',
 '287': '131443',
 '288': '131957',
 '289': '131959',
 '290': '131960',
 '291': '132094',
 '292': '132095',
 '293': '132777',
 '294': '132779',
 '295': '133211',
 '296': '133213',
 '297': '133215',
 '298': '133218',
 '299': '133313',
 '300': '133314',
 '301': '133315',
 '302': '133316',
 '303': '133317',
 '304': '133599',
 '305': '133600',
 '306': '133982',
 '307': '133984',
 '308': '134405',
 '309': '134406',
 '310': '134407',
 '311': '134408',
 '312': '134409',
 '313': '134411',
 '314': '134554',
 '315': '134555',
 '316': '134558',
 '317': '134687',
 '318': '134688',
 '319': '134878',
 '320': '135129',
 '321': '135131',
 '322': '135133',
 '323': '135135',
 '324': '135300',
 '325': '135730',
 '326': '135768',
 '327': '136425',
 '328': '136427',
 '329': '136431',
 '330': '136824',
 '331': '136826',
 '332': '137442',
 '333': '137444',
 '334': '137455',
 '335': '138070',
 '336': '138953',
 '337': '138963',
 '338': '138964',
 '339': '139320',
 '340': '139322',
 '341': '139324',
 '342': '139325',
 '343': '139326',
 '344': '139390',
 '345': '139391',
 '346': '139395',
 '347': '139396',
 '348': '139963',
 '349': '140398',
 '350': '140478',
 '351': '140479',
 '352': '141069',
 '353': '141071',
 '354': '141077',
 '355': '141079',
 '356': '141152',
 '357': '141554',
 '358': '141556',
 '359': '141696',
 '360': '141699',
 '361': '141726',
 '362': '141727',
 '363': '141889',
 '364': '141890',
 '365': '142010',
 '366': '142381',
 '367': '142832',
 '368': '142994',
 '369': '142996',
 '370': '143005',
 '371': '143685',
 '372': '144058',
 '373': '144215',
 '374': '144234',
 '375': '144667',
 '376': '145866',
 '377': '145870',
 '378': '145871',
 '379': '145872',
 '380': '147025',
 '381': '147029',
 '382': '147030',
 '383': '148581',
 '384': '148942',
 '385': '149001',
 '386': '149048',
 '387': '150903',
 '388': '157957',
 '389': '158782',
 '390': '159120',
 '391': '159121',
 '392': '159483',
 '393': '160746',
 '394': '161181',
 '395': '161207',
 '396': '161208',
 '397': '161209',
 '398': '161211',
 '399': '161928',
 '400': '161947',
 '401': '162001',
 '402': '164824',
 '403': '165535',
 '404': '166851',
 '405': '166855',
 '406': '170245',
 '407': '171444',
 '408': '173752',
 '409': '173754',
 '410': '174919',
 '411': '175242',
 '412': '175264',
 '413': '175320',
 '414': '178741',
 '415': '178742',
 '416': '178743',
 '417': '178744',
 '418': '178745',
 '419': '178746',
 '420': '178821',
 '421': '178823',
 '422': '180004',
 '423': '180005',
 '424': '180006',
 '425': '180350',
 '426': '182063',
 '427': '182065',
 '428': '182066',
 '429': '182493',
 '430': '182568',
 '431': '182569',
 '432': '182570',
 '433': '183460',
 '434': '183888',
 '435': '184066',
 '436': '184214',
 '437': '184547',
 '438': '184549',
 '439': '185459',
 '440': '185461',
 '441': '185465',
 '442': '187190',
 '443': '187192',
 '444': '189002',
 '445': '189082',
 '446': '189083',
 '447': '189085',
 '448': '189541',
 '449': '189543',
 '450': '189545',
 '451': '189545',
 '452': '189684',
 '453': '189686',
 '454': '189938',
 '455': '190497',
 '456': '191002',
 '457': '191437',
 '458': '191437',
 '459': '191495',
 '460': '191496',
 '461': '191974',
 '462': '192997',
 '463': '193034',
 '464': '193244',
 '465': '193246',
 '466': '194459',
 '467': '194461',
 '468': '194467',
 '469': '195591',
 '470': '195593',
 '471': '195594',
 '472': '195710',
 '473': '196767',
 '474': '198301',
 '475': '198996',
 '476': '198998',
 '477': '199647',
 '478': '200320',
 '479': '200322',
 '480': '200323',
 '481': '200326',
 '482': '200329',
 '483': '200875',
 '484': '200876',
 '485': '201316',
 '486': '201317',
 '487': '202778',
 '488': '202778',
 '489': '202780',
 '490': '203324',
 '491': '203326',
 '492': '203329',
 '493': '203330',
 '494': '203611',
 '495': '203697',
 '496': '203959',
 '497': '204578',
 '498': '204579',
 '499': '204865',
 '500': '205160',
 '501': '205162',
 '502': '205163',
 '503': '205165',
 '504': '205968',
 '505': '205975',
 '506': '206412',
 '507': '206414',
 '508': '206418',
 '509': '206420',
 '510': '207146',
 '511': '208759',
 '512': '209465',
 '513': '209582',
 '514': '209701',
 '515': '209935',
 '516': '209942',
 '517': '210400',
 '518': '210449',
 '519': '211843',
 '520': '213122',
 '521': '213179',
 '522': '213196',
 '523': '213397',
 '524': '213399',
 '525': '214372',
 '526': '214554',
 '527': '214556',
 '528': '215502',
 '529': '215507',
 '530': '215717',
 '531': '216291',
 '532': '216292',
 '533': '216622',
 '534': '216746',
 '535': '217784',
 '536': '217785',
 '537': '217880',
 '538': '218209',
 '539': '218984',
 '540': '218989',
 '541': '219135',
 '542': '220587',
 '543': '220589',
 '544': '220590',
 '545': '220592',
 '546': '221363',
 '547': '221443',
 '548': '221444',
 '549': '221558',
 '550': '221681',
 '551': '222683',
 '552': '225552',
 '553': '226772',
 '554': '226774',
 '555': '226775',
 '556': '226777',
 '557': '226779',
 '558': '226783',
 '559': '228163',
 '560': '228209',
 '561': '228210',
 '562': '228212',
 '563': '229192',
 '564': '230622',
 '565': '230636',
 '566': '230637',
 '567': '230638',
 '568': '230639',
 '569': '230698',
 '570': '231989',
 '571': '233238',
 '572': '233265',
 '573': '233266',
 '574': '233268',
 '575': '233269',
 '576': '233270',
 '577': '233272',
 '578': '234545',
 '579': '234546',
 '580': '234547',
 '581': '234548',
 '582': '235578',
 '583': '235775',
 '584': '238322',
 '585': '238323',
 '586': '238325',
 '587': '239762',
 '588': '241110',
 '589': '241111',
 '590': '242447',
 '591': '242448',
 '592': '242449',
 '593': '242450',
 '594': '243764',
 '595': '246405',
 '596': '246613',
 '597': '246614',
 '598': '246616',
 '599': '247733',
 '600': '247736',
 '601': '247737',
 '602': '247738',
 '603': '247740',
 '604': '249190',
 '605': '249191',
 '606': '249195',
 '607': '249197',
 '608': '249238',
 '609': '249298',
 '610': '249300',
 '611': '250563',
 '612': '250564',
 '613': '250568',
 '614': '250569',
 '615': '250570',
 '616': '250610',
 '617': '250611',
 '618': '250612',
 '619': '251938',
 '620': '251938',
 '621': '251940',
 '622': '251943',
 '623': '251944',
 '624': '251945',
 '625': '251949',
 '626': '252041',
 '627': '253444',
 '628': '254629',
 '629': '254631',
 '630': '254633',
 '631': '254634',
 '632': '254635',
 '633': '254636',
 '634': '256028',
 '635': '256086',
 '636': '256153',
 '637': '256154',
 '638': '256156',
 '639': '257371',
 '640': '257373',
 '641': '257376',
 '642': '257378',
 '643': '257497',
 '644': '257548',
 '645': '257549',
 '646': '257550',
 '647': '257551',
 '648': '257864',
 '649': '258768',
 '650': '258772',
 '651': '258773',
 '652': '258775',
 '653': '258861',
 '654': '258862',
 '655': '258864',
 '656': '260179',
 '657': '260180',
 '658': '260182',
 '659': '262662',
 '660': '262665',
 '661': '262667',
 '662': '262737',
 '663': '262738',
 '664': '263037',
 '665': '265156',
 '666': '265157',
 '667': '265159',
 '668': '265169',
 '669': '265817',
 '670': '265818',
 '671': '266495',
 '672': '266495',
 '673': '266500',
 '674': '266950',
 '675': '267079',
 '676': '267084',
 '677': '267085',
 '678': '267087',
 '679': '267088',
 '680': '268289',
 '681': '268290',
 '682': '268293',
 '683': '269791',
 '684': '269792',
 '685': '270807',
 '686': '270808',
 '687': '271226',
 '688': '271227',
 '689': '271238',
 '690': '271596',
 '691': '272861',
 '692': '272862',
 '693': '273997',
 '694': '274013',
 '695': '274081',
 '696': '274082',
 '697': '274609',
 '698': '274610',
 '699': '275168',
 '700': '275242',
 '701': '275243',
 '702': '276553',
 '703': '276554',
 '704': '276558',
 '705': '276559',
 '706': '276578',
 '707': '276642',
 '708': '276643',
 '709': '278283',
 '710': '278588',
 '711': '278593',
 '712': '278594',
 '713': '278923',
 '714': '280104',
 '715': '280108',
 '716': '280599',
 '717': '281325',
 '718': '283628',
 '719': '284240',
 '720': '284487',
 '721': '284488',
 '722': '284839',
 '723': '284840',
 '724': '284842',
 '725': '284843',
 '726': '284859',
 '727': '284863',
 '728': '284872',
 '729': '284918',
 '730': '284919',
 '731': '285888',
 '732': '285889',
 '733': '285893',
 '734': '285899',
 '735': '286583',
 '736': '286584',
 '737': '287115',
 '738': '287755',
 '739': '287756',
 '740': '288447',
 '741': '288457',
 '742': '288458',
 '743': '289069',
 '744': '289072',
 '745': '289620',
 '746': '289622',
 '747': '289626',
 '748': '289639',
 '749': '290164',
 '750': '292720',
 '751': '293901',
 '752': '293902',
 '753': '294625',
 '754': '294630',
 '755': '294631',
 '756': '294640',
 '757': '294648',
 '758': '295276',
 '759': '295884',
 '760': '295888',
 '761': '295889',
 '762': '296530',
 '763': '296530',
 '764': '296536',
 '765': '296903',
 '766': '297265',
 '767': '297268',
 '768': '297269',
 '769': '299835',
 '770': '299837',
 '771': '299857',
 '772': '300436',
 '773': '300439',
 '774': '300440',
 '775': '301082',
 '776': '301083',
 '777': '301579',
 '778': '301871',
 '779': '301872',
 '780': '302246',
 '781': '302276',
 '782': '302277',
 '783': '303932',
 '784': '303933',
 '785': '304733',
 '786': '304798',
 '787': '305183',
 '788': '305184',
 '789': '305199',
 '790': '306472',
 '791': '306473',
 '792': '306536',
 '793': '307354',
 '794': '307772',
 '795': '307776',
 '796': '307793',
 '797': '307798',
 '798': '308746',
 '799': '308749',
 '800': '308749',
 '801': '308751',
 '802': '308753',
 '803': '308755',
 '804': '308757',
 '805': '308759',
 '806': '308760',
 '807': '309241',
 '808': '309242',
 '809': '309314',
 '810': '309317',
 '811': '309330',
 '812': '309332',
 '813': '309641',
 '814': '310091',
 '815': '310463',
 '816': '310467',
 '817': '311371',
 '818': '311410',
 '819': '312284',
 '820': '312745',
 '821': '312748',
 '822': '312752',
 '823': '312754',
 '824': '312756',
 '825': '312758',
 '826': '313563',
 '827': '314569',
 '828': '314570',
 '829': '314570',
 '830': '314571',
 '831': '314572',
 '832': '314881',
 '833': '315778',
 '834': '316016',
 '835': '316017',
 '836': '316018',
 '837': '316423',
 '838': '316940',
 '839': '316965',
 '840': '316966',
 '841': '316968',
 '842': '316972',
 '843': '316973',
 '844': '316974',
 '845': '316975',
 '846': '316979',
 '847': '316980',
 '848': '316982',
 '849': '316986',
 '850': '316987',
 '851': '316988',
 '852': '316989',
 '853': '316995',
 '854': '318196',
 '855': '318197',
 '856': '318290',
 '857': '318966',
 '858': '320098',
 '859': '320897',
 '860': '321440',
 '861': '321765',
 '862': '321767',
 '863': '321768',
 '864': '321820',
 '865': '321861',
 '866': '321876',
 '867': '321877',
 '868': '321878',
 '869': '321879',
 '870': '322969',
 '871': '323303',
 '872': '323341',
 '873': '323342',
 '874': '323343',
 '875': '323613',
 '876': '324334',
 '877': '324409',
 '878': '324410',
 '879': '324426',
 '880': '324427',
 '881': '324429',
 '882': '324688',
 '883': '325525',
 '884': '325526',
 '885': '326802',
 '886': '326803',
 '887': '326805',
 '888': '327604',
 '889': '327669',
 '890': '328370',
 '891': '328371',
 '892': '328373',
 '893': '328412',
 '894': '328659',
 '895': '328660',
 '896': '329163',
 '897': '329166',
 '898': '329636',
 '899': '329902',
 '900': '330319',
 '901': '330321',
 '902': '330328',
 '903': '330330',
 '904': '330332',
 '905': '330342',
 '906': '331172',
 '907': '331173',
 '908': '331716',
 '909': '332168',
 '910': '332171',
 '911': '333014',
 '912': '333117',
 '913': '333551',
 '914': '333552',
 '915': '333903',
 '916': '334914',
 '917': '334915',
 '918': '334917',
 '919': '335198',
 '920': '335600',
 '921': '336402',
 '922': '336403',
 '923': '337409',
 '924': '337410',
 '925': '337412',
 '926': '338664',
 '927': '338673',
 '928': '338674',
 '929': '338675',
 '930': '338676',
 '931': '340067',
 '932': '340070',
 '933': '340145',
 '934': '340146',
 '935': '340148',
 '936': '340438',
 '937': '340837',
 '938': '341658',
 '939': '342462',
 '940': '343173',
 '941': '343579',
 '942': '343582',
 '943': '343583',
 '944': '345023',
 '945': '345024',
 '946': '345061',
 '947': '345347',
 '948': '346267',
 '949': '346269',
 '950': '346381',
 '951': '346383',
 '952': '347233',
 '953': '347578',
 '954': '347580',
 '955': '348083',
 '956': '348500',
 '957': '348972',
 '958': '348975',
 '959': '348976',
 '960': '348978',
 '961': '349849',
 '962': '349857',
 '963': '351310',
 '964': '351311',
 '965': '351337',
 '966': '351747',
 '967': '352155',
 '968': '352638',
 '969': '353093',
 '970': '353111',
 '971': '353113',
 '972': '353115',
 '973': '353633',
 '974': '354673',
 '975': '354675',
 '976': '354790',
 '977': '354795',
 '978': '355097',
 '979': '355098',
 '980': '355668',
 '981': '355669',
 '982': '356125',
 '983': '356129',
 '984': '357621',
 '985': '357624',
 '986': '357628',
 '987': '358523',
 '988': '358903',
 '989': '358905',
 '990': '358906',
 '991': '358907',
 '992': '359967',
 '993': '359969',
 '994': '359970',
 '995': '360291',
 '996': '360293',
 '997': '360294',
 '998': '360720',
 '999': '360724',
 ...}

In [12]:
ident_index_map = data.ident_index_map()

In [82]:
ident_index_map

{20: 0,
 3225: 1,
 3319: 2,
 3435: 3,
 3495: 4,
 3504: 5,
 4872: 6,
 4873: 7,
 4877: 8,
 4895: 9,
 4896: 10,
 5133: 11,
 5134: 12,
 5150: 13,
 5181: 14,
 5182: 15,
 5183: 16,
 5190: 17,
 5191: 18,
 5193: 19,
 6656: 20,
 7966: 21,
 7978: 22,
 7989: 23,
 7990: 24,
 10272: 25,
 10274: 26,
 52853: 27,
 59070: 28,
 10662: 29,
 10664: 30,
 10688: 31,
 16848: 32,
 16849: 33,
 16850: 34,
 16852: 35,
 16853: 36,
 16855: 37,
 16856: 38,
 8653: 39,
 8654: 40,
 8655: 41,
 8656: 42,
 8657: 43,
 16892: 44,
 61379: 45,
 106702: 46,
 10: 47,
 23: 48,
 26: 49,
 27: 50,
 28: 51,
 61: 52,
 69: 53,
 70: 54,
 71: 55,
 75: 56,
 76: 57,
 81: 58,
 227: 59,
 502: 60,
 903: 61,
 920: 62,
 921: 63,
 946: 64,
 953: 65,
 1074: 66,
 1075: 67,
 1086: 68,
 1097: 69,
 1125: 70,
 1134: 71,
 1150: 72,
 1174: 73,
 1175: 74,
 1571: 75,
 2005: 76,
 2010: 77,
 2038: 78,
 2044: 79,
 2047: 80,
 2050: 81,
 2053: 82,
 2057: 83,
 2058: 84,
 2064: 85,
 2065: 86,
 2066: 87,
 2071: 88,
 2076: 89,
 2083: 90,
 2084: 91,
 2085: 92,
 2087: 93,
 2099: 94,
 2107: 95,
 2493: 96,
 2494: 97,
 2501: 98,
 2510: 99,
 2529: 100,
 2540: 101,
 2557: 102,
 2558: 103,
 2559: 104,
 2794: 105,
 2833: 106,
 2840: 107,
 2841: 108,
 2871: 109,
 2873: 110,
 2892: 111,
 2918: 112,
 3020: 113,
 3037: 114,
 3041: 115,
 3047: 116,
 3054: 117,
 3060: 118,
 3082: 119,
 3083: 120,
 3094: 121,
 3415: 122,
 3426: 123,
 3632: 124,
 3641: 125,
 3653: 126,
 3664: 127,
 3685: 128,
 3857: 129,
 3858: 130,
 4123: 131,
 4126: 132,
 4303: 133,
 4304: 134,
 4305: 135,
 4307: 136,
 4308: 137,
 4958: 138,
 4964: 139,
 4965: 140,
 5559: 141,
 5560: 142,
 5561: 143,
 5562: 144,
 5563: 145,
 5564: 146,
 5565: 147,
 5566: 148,
 5567: 149,
 5568: 150,
 7003: 151,
 9440: 152,
 9441: 153,
 9463: 154,
 9467: 155,
 9469: 156,
 9470: 157,
 9471: 158,
 9472: 159,
 9487: 160,
 9491: 161,
 11776: 162,
 12161: 163,
 12162: 164,
 12163: 165,
 12164: 166,
 12165: 167,
 12170: 168,
 12171: 169,
 12172: 170,
 12173: 171,
 12210: 172,
 12221: 173,
 12227: 174,
 12232: 175,
 12469: 176,
 15276: 177,
 15277: 178,
 16228: 179,
 16236: 180,
 16897: 181,
 17552: 182,
 17553: 183,
 17937: 184,
 19921: 185,
 21024: 186,
 21026: 187,
 21027: 188,
 21052: 189,
 21061: 190,
 21901: 191,
 22979: 192,
 25973: 193,
 25974: 194,
 25975: 195,
 25976: 196,
 25977: 197,
 25978: 198,
 25979: 199,
 25980: 200,
 28051: 201,
 28052: 202,
 28055: 203,
 29533: 204,
 33207: 205,
 35407: 206,
 35408: 207,
 35409: 208,
 35410: 209,
 35423: 210,
 35425: 211,
 37329: 212,
 37330: 213,
 38618: 214,
 40626: 215,
 40627: 216,
 41969: 217,
 54087: 218,
 54088: 219,
 54090: 220,
 54091: 221,
 54092: 222,
 54297: 223,
 58996: 224,
 89055: 225,
 89061: 226,
 91675: 227,
 91913: 228,
 92600: 229,
 92602: 230,
 92603: 231,
 92604: 232,
 92614: 233,
 92618: 234,
 92619: 235,
 92621: 236,
 92622: 237,
 92624: 238,
 92625: 239,
 92626: 240,
 92627: 241,
 92628: 242,
 92650: 243,
 92651: 244,
 95613: 245,
 96432: 246,
 96433: 247,
 96434: 248,
 98326: 249,
 98924: 250,
 105567: 251,
 107551: 252,
 107552: 253,
 111424: 254,
 111425: 255,
 115658: 256,
 117678: 257,
 119102: 258,
 119103: 259,
 119105: 260,
 119106: 261,
 119108: 262,
 119109: 263,
 119117: 264,
 119120: 265,
 3750: 266,
 3751: 267,
 3752: 268,
 3753: 269,
 3754: 270,
 3755: 271,
 3756: 272,
 4395: 273,
 4399: 274,
 4402: 275,
 4403: 276,
 4404: 277,
 4405: 278,
 4406: 279,
 4407: 280,
 4408: 281,
 4409: 282,
 4410: 283,
 4412: 284,
 4413: 285,
 4414: 286,
 4415: 287,
 4416: 288,
 36610: 289,
 36611: 290,
 36612: 291,
 44494: 292,
 44495: 293,
 44496: 294,
 92129: 295,
 95818: 296,
 95819: 297,
 95820: 298,
 117686: 299,
 36: 300,
 63: 301,
 73: 302,
 721: 303,
 855: 304,
 2268: 305,
 2345: 306,
 2362: 307,
 2378: 308,
 2572: 309,
 4312: 310,
 4473: 311,
 4946: 312,
 4947: 313,
 4954: 314,
 4955: 315,
 4956: 316,
 4957: 317,
 5163: 318,
 5506: 319,
 12154: 320,
 12155: 321,
 12198: 322,
 12230: 323,
 12231: 324,
 12233: 325,
 12234: 326,
 12236: 327,
 12238: 328,
 21065: 329,
 25986: 330,
 25987: 331,
 27591: 332,
 28056: 333,
 28058: 334,
 36326: 335,
 36339: 336,
 37760: 337,
 37766: 338,
 37768: 339,
 37769: 340,
 37782: 341,
 37784: 342,
 37789: 343,
 37792: 344,
 40637: 345,
 40638: 346,
 40645: 347,
 40647: 348,
 44148: 349,
 44157: 350,
 44161: 351,
 44162: 352,
 44164: 353,
 44165: 354,
 44170: 355,
 44173: 356,
 45852: 357,
 46829: 358,
 54097: 359,
 54099: 360,
 54295: 361,
 54303: 362,
 54686: 363,
 54687: 364,
 54688: 365,
 54693: 366,
 54694: 367,
 54697: 368,
 54699: 369,
 54701: 370,
 54703: 371,
 54706: 372,
 54718: 373,
 54843: 374,
 54844: 375,
 54846: 376,
 54847: 377,
 54860: 378,
 54861: 379,
 60673: 380,
 61369: 381,
 61374: 382,
 61384: 383,
 68224: 384,
 68226: 385,
 68228: 386,
 68229: 387,
 68232: 388,
 68241: 389,
 68245: 390,
 68246: 391,
 68247: 392,
 68248: 393,
 68249: 394,
 68254: 395,
 68255: 396,
 68256: 397,
 68257: 398,
 68258: 399,
 68259: 400,
 68261: 401,
 68262: 402,
 68264: 403,
 68266: 404,
 68270: 405,
 68271: 406,
 68277: 407,
 68280: 408,
 68281: 409,
 68282: 410,
 68283: 411,
 68284: 412,
 68285: 413,
 68290: 414,
 68296: 415,
 68300: 416,
 68301: 417,
 68302: 418,
 68303: 419,
 68304: 420,
 68305: 421,
 68307: 422,
 68308: 423,
 68309: 424,
 68310: 425,
 68312: 426,
 68314: 427,
 68316: 428,
 68317: 429,
 68320: 430,
 68321: 431,
 68322: 432,
 68324: 433,
 68325: 434,
 68334: 435,
 68338: 436,
 68341: 437,
 68344: 438,
 68345: 439,
 68350: 440,
 68351: 441,
 69508: 442,
 86372: 443,
 86373: 444,
 96367: 445,
 96368: 446,
 96369: 447,
 96373: 448,
 97735: 449,
 97736: 450,
 102043: 451,
 102591: 452,
 102735: 453,
 104561: 454,
 104562: 455,
 104564: 456,
 104565: 457,
 104566: 458,
 104568: 459,
 108805: 460,
 119272: 461,
 119274: 462,
 119279: 463,
 119282: 464,
 36130: 465,
 36131: 466,
 36132: 467,
 36133: 468,
 36135: 469,
 36136: 470,
 36139: 471,
 36140: 472,
 36141: 473,
 36145: 474,
 36149: 475,
 36150: 476,
 36151: 477,
 36152: 478,
 36154: 479,
 36155: 480,
 36156: 481,
 37762: 482,
 53839: 483,
 54299: 484,
 68268: 485,
 68273: 486,
 108792: 487,
 108793: 488,
 108794: 489,
 98919: 490,
 4411: 491,
 16: 492,
 37: 493,
 43: 494,
 84: 495,
 92: 496,
 123: 497,
 125: 498,
 619: 499,
 1182: 500,
 1188: 501,
 1201: 502,
 1210: 503,
 1216: 504,
 1241: 505,
 1248: 506,
 1251: 507,
 1257: 508,
 1264: 509,
 1270: 510,
 1287: 511,
 1288: 512,
 1305: 513,
 1306: 514,
 1307: 515,
 1308: 516,
 1310: 517,
 1312: 518,
 1313: 519,
 1315: 520,
 1324: 521,
 3526: 522,
 3530: 523,
 3533: 524,
 3539: 525,
 3556: 526,
 3558: 527,
 3571: 528,
 13494: 529,
 13495: 530,
 13497: 531,
 13498: 532,
 13499: 533,
 13503: 534,
 13504: 535,
 13506: 536,
 13507: 537,
 13508: 538,
 13511: 539,
 13512: 540,
 13514: 541,
 13515: 542,
 13516: 543,
 13517: 544,
 13518: 545,
 13520: 546,
 13522: 547,
 13523: 548,
 13524: 549,
 13536: 550,
 31910: 551,
 31911: 552,
 31912: 553,
 31913: 554,
 31914: 555,
 31915: 556,
 31916: 557,
 31917: 558,
 31920: 559,
 53097: 560,
 101121: 561,
 108787: 562,
 112530: 563,
 112531: 564,
 117554: 565,
 7412: 566,
 19948: 567,
 91655: 568,
 102128: 569,
 2767: 570,
 3084: 571,
 3085: 572,
 3086: 573,
 3099: 574,
 1706: 575,
 1782: 576,
 1790: 577,
 1795: 578,
 1835: 579,
 1842: 580,
 5348: 581,
 7498: 582,
 9494: 583,
 9539: 584,
 9540: 585,
 44351: 586,
 83347: 587,
 83353: 588,
 83354: 589,
 97963: 590,
 97964: 591,
 97965: 592,
 97966: 593,
 100634: 594,
 100635: 595,
 33: 596,
 1021: 597,
 1557: 598,
 1558: 599,
 1568: 600,
 1597: 601,
 1641: 602,
 1654: 603,
 1655: 604,
 1667: 605,
 2011: 606,
 2051: 607,
 2098: 608,
 2763: 609,
 4950: 610,
 4959: 611,
 5152: 612,
 6222: 613,
 6224: 614,
 7416: 615,
 9462: 616,
 9468: 617,
 12218: 618,
 12464: 619,
 16022: 620,
 16024: 621,
 16026: 622,
 16030: 623,
 16036: 624,
 16041: 625,
 16043: 626,
 16286: 627,
 16287: 628,
 16288: 629,
 16290: 630,
 16291: 631,
 21058: 632,
 27599: 633,
 27600: 634,
 29058: 635,
 29060: 636,
 29061: 637,
 29062: 638,
 29063: 639,
 29064: 640,
 29065: 641,
 29066: 642,
 29067: 643,
 29068: 644,
 29069: 645,
 29070: 646,
 29073: 647,
 29075: 648,
 29076: 649,
 29079: 650,
 29080: 651,
 30063: 652,
 33200: 653,
 33201: 654,
 33202: 655,
 35411: 656,
 35413: 657,
 35414: 658,
 35415: 659,
 35416: 660,
 35418: 661,
 35419: 662,
 35421: 663,
 35422: 664,
 35603: 665,
 36327: 666,
 38715: 667,
 38716: 668,
 39080: 669,
 39090: 670,
 39092: 671,
 39095: 672,
 44227: 673,
 52736: 674,
 52738: 675,
 52740: 676,
 52741: 677,
 52742: 678,
 52743: 679,
 52744: 680,
 52745: 681,
 52746: 682,
 52748: 683,
 52749: 684,
 52750: 685,
 52751: 686,
 53846: 687,
 53851: 688,
 53859: 689,
 53867: 690,
 54096: 691,
 54098: 692,
 54101: 693,
 54102: 694,
 54112: 695,
 59000: 696,
 59002: 697,
 59003: 698,
 59004: 699,
 59104: 700,
 91681: 701,
 94617: 702,
 95600: 703,
 100167: 704,
 100930: 705,
 100939: 706,
 101685: 707,
 101690: 708,
 101692: 709,
 102583: 710,
 102587: 711,
 102613: 712,
 113630: 713,
 8073: 714,
 9202: 715,
 9203: 716,
 54684: 717,
 54695: 718,
 106703: 719,
 7306: 720,
 9828: 721,
 96411: 722,
 113834: 723,
 113836: 724,
 113841: 725,
 3820: 726,
 4479: 727,
 4482: 728,
 4483: 729,
 4484: 730,
 4486: 731,
 4488: 732,
 4489: 733,
 4491: 734,
 4492: 735,
 4493: 736,
 4496: 737,
 4497: 738,
 8032: 739,
 9044: 740,
 17910: 741,
 41766: 742,
 54863: 743,
 59: 744,
 1941: 745,
 13534: 746,
 16497: 747,
 18893: 748,
 18907: 749,
 18920: 750,
 19018: 751,
 19041: 752,
 19067: 753,
 19080: 754,
 19089: 755,
 19108: 756,
 19114: 757,
 19120: 758,
 19122: 759,
 19126: 760,
 19131: 761,
 19137: 762,
 19188: 763,
 19198: 764,
 19204: 765,
 19210: 766,
 19240: 767,
 19244: 768,
 19246: 769,
 19251: 770,
 19256: 771,
 19260: 772,
 19264: 773,
 19269: 774,
 19273: 775,
 19278: 776,
 19283: 777,
 19287: 778,
 19294: 779,
 19301: 780,
 19307: 781,
 19312: 782,
 19315: 783,
 19395: 784,
 19399: 785,
 19405: 786,
 19471: 787,
 19479: 788,
 19486: 789,
 19489: 790,
 19506: 791,
 19535: 792,
 19541: 793,
 19545: 794,
 19548: 795,
 19551: 796,
 19556: 797,
 19559: 798,
 19568: 799,
 19571: 800,
 19582: 801,
 19585: 802,
 19595: 803,
 19599: 804,
 19602: 805,
 19608: 806,
 19614: 807,
 19621: 808,
 19625: 809,
 19629: 810,
 19646: 811,
 19650: 812,
 19661: 813,
 19665: 814,
 19668: 815,
 19674: 816,
 19687: 817,
 19691: 818,
 19708: 819,
 19718: 820,
 19722: 821,
 19728: 822,
 19742: 823,
 21448: 824,
 29548: 825,
 29549: 826,
 29550: 827,
 29552: 828,
 29553: 829,
 29554: 830,
 29555: 831,
 29556: 832,
 29557: 833,
 29558: 834,
 29559: 835,
 29560: 836,
 29561: 837,
 29562: 838,
 29613: 839,
 29614: 840,
 29616: 841,
 29621: 842,
 36636: 843,
 36637: 844,
 36638: 845,
 37531: 846,
 37537: 847,
 55388: 848,
 86632: 849,
 86636: 850,
 86638: 851,
 86639: 852,
 86645: 853,
 86646: 854,
 93722: 855,
 93723: 856,
 4572: 857,
 4577: 858,
 4581: 859,
 4584: 860,
 4587: 861,
 4593: 862,
 4598: 863,
 5953: 864,
 5956: 865,
 5957: 866,
 6703: 867,
 7352: 868,
 7353: 869,
 7360: 870,
 7363: 871,
 7369: 872,
 7405: 873,
 7407: 874,
 7799: 875,
 7801: 876,
 8078: 877,
 8080: 878,
 8081: 879,
 8082: 880,
 8083: 881,
 8084: 882,
 8085: 883,
 8086: 884,
 9353: 885,
 9358: 886,
 9359: 887,
 18864: 888,
 18865: 889,
 18866: 890,
 18867: 891,
 18868: 892,
 18869: 893,
 18870: 894,
 18871: 895,
 18872: 896,
 18873: 897,
 18874: 898,
 18876: 899,
 18878: 900,
 18879: 901,
 18883: 902,
 34228: 903,
 91646: 904,
 95718: 905,
 95721: 906,
 95722: 907,
 95723: 908,
 95736: 909,
 95737: 910,
 95849: 911,
 95852: 912,
 95853: 913,
 95854: 914,
 95855: 915,
 95857: 916,
 95858: 917,
 95859: 918,
 98573: 919,
 110302: 920,
 166: 921,
 844: 922,
 1339: 923,
 1377: 924,
 2489: 925,
 2497: 926,
 2541: 927,
 2551: 928,
 2575: 929,
 2576: 930,
 2583: 931,
 2713: 932,
 2795: 933,
 2798: 934,
 2799: 935,
 2800: 936,
 2845: 937,
 2851: 938,
 6902: 939,
 6904: 940,
 6905: 941,
 6907: 942,
 6909: 943,
 6910: 944,
 6911: 945,
 6912: 946,
 8637: 947,
 8638: 948,
 8678: 949,
 9480: 950,
 10579: 951,
 12225: 952,
 12226: 953,
 16028: 954,
 16032: 955,
 16044: 956,
 16289: 957,
 16292: 958,
 16293: 959,
 22973: 960,
 22977: 961,
 27598: 962,
 33204: 963,
 33205: 964,
 33206: 965,
 35152: 966,
 35153: 967,
 37464: 968,
 38608: 969,
 43906: 970,
 43910: 971,
 44146: 972,
 44147: 973,
 44155: 974,
 44188: 975,
 51871: 976,
 51877: 977,
 51878: 978,
 52362: 979,
 52452: 980,
 52455: 981,
 53836: 982,
 53838: 983,
 53843: 984,
 53850: 985,
 53852: 986,
 53853: 987,
 53854: 988,
 53855: 989,
 53856: 990,
 53860: 991,
 53861: 992,
 53863: 993,
 53870: 994,
 53871: 995,
 53875: 996,
 58995: 997,
 91686: 998,
 105689: 999,
 ...}

Create a mapping of ident to activity.activity_id (which is named ID)

In [91]:
print(ident_activityID_map.keys())

dict_keys([20, 3225, 3319, 3435, 3495, 3504, 4872, 4873, 4877, 4895, 4896, 5133, 5134, 5150, 5181, 5182, 5183, 5190, 5191, 5193, 6656, 7966, 7978, 7989, 7990, 10272, 10274, 52853, 59070, 10662, 10664, 10688, 16848, 16849, 16850, 16852, 16853, 16855, 16856, 8653, 8654, 8655, 8656, 8657, 16892, 61379, 106702, 10, 23, 26, 27, 28, 61, 69, 70, 71, 75, 76, 81, 227, 502, 903, 920, 921, 946, 953, 1074, 1075, 1086, 1097, 1125, 1134, 1150, 1174, 1175, 1571, 2005, 2010, 2038, 2044, 2047, 2050, 2053, 2057, 2058, 2064, 2065, 2066, 2071, 2076, 2083, 2084, 2085, 2087, 2099, 2107, 2493, 2494, 2501, 2510, 2529, 2540, 2557, 2558, 2559, 2794, 2833, 2840, 2841, 2871, 2873, 2892, 2918, 3020, 3037, 3041, 3047, 3054, 3060, 3082, 3083, 3094, 3415, 3426, 3632, 3641, 3653, 3664, 3685, 3857, 3858, 4123, 4126, 4303, 4304, 4305, 4307, 4308, 4958, 4964, 4965, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 7003, 9440, 9441, 9463, 9467, 9469, 9470, 9471, 9472, 9487, 9491, 11776, 12161, 12162, 12163, 12164, 12165, 12170, 12171, 12172, 12173, 12210, 12221, 12227, 12232, 12469, 15276, 15277, 16228, 16236, 16897, 17552, 17553, 17937, 19921, 21024, 21026, 21027, 21052, 21061, 21901, 22979, 25973, 25974, 25975, 25976, 25977, 25978, 25979, 25980, 28051, 28052, 28055, 29533, 33207, 35407, 35408, 35409, 35410, 35423, 35425, 37329, 37330, 38618, 40626, 40627, 41969, 54087, 54088, 54090, 54091, 54092, 54297, 58996, 89055, 89061, 91675, 91913, 92600, 92602, 92603, 92604, 92614, 92618, 92619, 92621, 92622, 92624, 92625, 92626, 92627, 92628, 92650, 92651, 95613, 96432, 96433, 96434, 98326, 98924, 105567, 107551, 107552, 111424, 111425, 115658, 117678, 119102, 119103, 119105, 119106, 119108, 119109, 119117, 119120, 3750, 3751, 3752, 3753, 3754, 3755, 3756, 4395, 4399, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409, 4410, 4412, 4413, 4414, 4415, 4416, 36610, 36611, 36612, 44494, 44495, 44496, 92129, 95818, 95819, 95820, 117686, 36, 63, 73, 721, 855, 2268, 2345, 2362, 2378, 2572, 4312, 4473, 4946, 4947, 4954, 4955, 4956, 4957, 5163, 5506, 12154, 12155, 12198, 12230, 12231, 12233, 12234, 12236, 12238, 21065, 25986, 25987, 27591, 28056, 28058, 36326, 36339, 37760, 37766, 37768, 37769, 37782, 37784, 37789, 37792, 40637, 40638, 40645, 40647, 44148, 44157, 44161, 44162, 44164, 44165, 44170, 44173, 45852, 46829, 54097, 54099, 54295, 54303, 54686, 54687, 54688, 54693, 54694, 54697, 54699, 54701, 54703, 54706, 54718, 54843, 54844, 54846, 54847, 54860, 54861, 60673, 61369, 61374, 61384, 68224, 68226, 68228, 68229, 68232, 68241, 68245, 68246, 68247, 68248, 68249, 68254, 68255, 68256, 68257, 68258, 68259, 68261, 68262, 68264, 68266, 68270, 68271, 68277, 68280, 68281, 68282, 68283, 68284, 68285, 68290, 68296, 68300, 68301, 68302, 68303, 68304, 68305, 68307, 68308, 68309, 68310, 68312, 68314, 68316, 68317, 68320, 68321, 68322, 68324, 68325, 68334, 68338, 68341, 68344, 68345, 68350, 68351, 69508, 86372, 86373, 96367, 96368, 96369, 96373, 97735, 97736, 102043, 102591, 102735, 104561, 104562, 104564, 104565, 104566, 104568, 108805, 119272, 119274, 119279, 119282, 36130, 36131, 36132, 36133, 36135, 36136, 36139, 36140, 36141, 36145, 36149, 36150, 36151, 36152, 36154, 36155, 36156, 37762, 53839, 54299, 68268, 68273, 108792, 108793, 108794, 98919, 4411, 16, 37, 43, 84, 92, 123, 125, 619, 1182, 1188, 1201, 1210, 1216, 1241, 1248, 1251, 1257, 1264, 1270, 1287, 1288, 1305, 1306, 1307, 1308, 1310, 1312, 1313, 1315, 1324, 3526, 3530, 3533, 3539, 3556, 3558, 3571, 13494, 13495, 13497, 13498, 13499, 13503, 13504, 13506, 13507, 13508, 13511, 13512, 13514, 13515, 13516, 13517, 13518, 13520, 13522, 13523, 13524, 13536, 31910, 31911, 31912, 31913, 31914, 31915, 31916, 31917, 31920, 53097, 101121, 108787, 112530, 112531, 117554, 7412, 19948, 91655, 102128, 2767, 3084, 3085, 3086, 3099, 1706, 1782, 1790, 1795, 1835, 1842, 5348, 7498, 9494, 9539, 9540, 44351, 83347, 83353, 83354, 97963, 97964, 97965, 97966, 100634, 100635, 33, 1021, 1557, 1558, 1568, 1597, 1641, 1654, 1655, 1667, 2011, 2051, 2098, 2763, 4950, 4959, 5152, 6222, 6224, 7416, 9462, 9468, 12218, 12464, 16022, 16024, 16026, 16030, 16036, 16041, 16043, 16286, 16287, 16288, 16290, 16291, 21058, 27599, 27600, 29058, 29060, 29061, 29062, 29063, 29064, 29065, 29066, 29067, 29068, 29069, 29070, 29073, 29075, 29076, 29079, 29080, 30063, 33200, 33201, 33202, 35411, 35413, 35414, 35415, 35416, 35418, 35419, 35421, 35422, 35603, 36327, 38715, 38716, 39080, 39090, 39092, 39095, 44227, 52736, 52738, 52740, 52741, 52742, 52743, 52744, 52745, 52746, 52748, 52749, 52750, 52751, 53846, 53851, 53859, 53867, 54096, 54098, 54101, 54102, 54112, 59000, 59002, 59003, 59004, 59104, 91681, 94617, 95600, 100167, 100930, 100939, 101685, 101690, 101692, 102583, 102587, 102613, 113630, 8073, 9202, 9203, 54684, 54695, 106703, 7306, 9828, 96411, 113834, 113836, 113841, 3820, 4479, 4482, 4483, 4484, 4486, 4488, 4489, 4491, 4492, 4493, 4496, 4497, 8032, 9044, 17910, 41766, 54863, 59, 1941, 13534, 16497, 18893, 18907, 18920, 19018, 19041, 19067, 19080, 19089, 19108, 19114, 19120, 19122, 19126, 19131, 19137, 19188, 19198, 19204, 19210, 19240, 19244, 19246, 19251, 19256, 19260, 19264, 19269, 19273, 19278, 19283, 19287, 19294, 19301, 19307, 19312, 19315, 19395, 19399, 19405, 19471, 19479, 19486, 19489, 19506, 19535, 19541, 19545, 19548, 19551, 19556, 19559, 19568, 19571, 19582, 19585, 19595, 19599, 19602, 19608, 19614, 19621, 19625, 19629, 19646, 19650, 19661, 19665, 19668, 19674, 19687, 19691, 19708, 19718, 19722, 19728, 19742, 21448, 29548, 29549, 29550, 29552, 29553, 29554, 29555, 29556, 29557, 29558, 29559, 29560, 29561, 29562, 29613, 29614, 29616, 29621, 36636, 36637, 36638, 37531, 37537, 55388, 86632, 86636, 86638, 86639, 86645, 86646, 93722, 93723, 4572, 4577, 4581, 4584, 4587, 4593, 4598, 5953, 5956, 5957, 6703, 7352, 7353, 7360, 7363, 7369, 7405, 7407, 7799, 7801, 8078, 8080, 8081, 8082, 8083, 8084, 8085, 8086, 9353, 9358, 9359, 18864, 18865, 18866, 18867, 18868, 18869, 18870, 18871, 18872, 18873, 18874, 18876, 18878, 18879, 18883, 34228, 91646, 95718, 95721, 95722, 95723, 95736, 95737, 95849, 95852, 95853, 95854, 95855, 95857, 95858, 95859, 98573, 110302, 166, 844, 1339, 1377, 2489, 2497, 2541, 2551, 2575, 2576, 2583, 2713, 2795, 2798, 2799, 2800, 2845, 2851, 6902, 6904, 6905, 6907, 6909, 6910, 6911, 6912, 8637, 8638, 8678, 9480, 10579, 12225, 12226, 16028, 16032, 16044, 16289, 16292, 16293, 22973, 22977, 27598, 33204, 33205, 33206, 35152, 35153, 37464, 38608, 43906, 43910, 44146, 44147, 44155, 44188, 51871, 51877, 51878, 52362, 52452, 52455, 53836, 53838, 53843, 53850, 53852, 53853, 53854, 53855, 53856, 53860, 53861, 53863, 53870, 53871, 53875, 58995, 91686, 105689, 109437, 109438, 109444, 109445, 111350, 112483, 118172, 67, 1043, 1051, 1052, 1053, 1101, 1139, 1161, 1171, 1181, 1185, 1196, 1217, 1252, 1259, 1283, 1300, 1314, 1316, 2002, 2009, 2017, 2026, 2033, 2041, 2042, 2080, 2082, 2095, 3263, 11447, 18948, 19008, 19223, 19248, 19280, 19537, 19564, 19592, 20123, 53204, 77346, 77347, 77348, 77349, 77350, 77351, 77352, 77353, 77354, 77355, 77356, 77357, 83397, 83398, 83399, 83400, 83401, 83402, 83403, 83404, 83406, 93540, 94209, 94210, 94211, 94212, 94213, 94214, 94215, 94216, 94217, 94218, 94219, 94221, 94222, 94225, 113265, 113514, 113515, 113516, 113517, 113518, 113519, 113520, 113521, 113522, 113523, 113524, 113525, 115659, 115982, 115984, 1485, 101848, 87, 88, 89, 90, 99, 117, 119, 126, 127, 132, 138, 341, 349, 352, 358, 375, 380, 387, 390, 391, 397, 399, 424, 425, 428, 450, 495, 503, 508, 524, 531, 532, 539, 543, 550, 864, 879, 887, 888, 891, 915, 917, 929, 930, 939, 942, 947, 963, 964, 975, 992, 993, 1010, 1015, 1023, 1031, 1194, 1208, 1213, 1226, 1304, 1322, 1348, 1354, 1362, 1409, 1410, 1438, 1908, 1917, 1967, 1990, 2712, 2733, 3238, 3255, 3270, 3279, 3307, 3308, 3309, 3371, 3386, 3406, 3412, 3442, 3475, 3606, 4345, 4350, 4354, 4355, 4455, 4456, 4457, 4458, 4459, 4460, 4461, 4528, 4529, 4530, 4532, 4533, 4534, 4535, 4536, 4537, 4539, 6075, 6076, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6437, 6438, 6439, 6441, 6442, 6443, 6444, 6445, 6446, 6899, 11874, 11875, 11877, 11879, 11880, 11881, 12108, 12109, 12110, 12111, 15279, 15280, 15281, 15283, 15284, 15285, 15286, 15288, 15289, 15290, 15291, 17632, 17633, 17634, 17635, 17636, 17638, 17639, 17640, 17641, 17642, 17643, 17645, 17646, 17647, 17648, 101904, 101924, 101939, 101951, 94, 97, 103, 106, 115, 122, 135, 139, 149, 1447, 1460, 1469, 1480, 1483, 1491, 115329, 115330, 115331, 480, 5823, 5824, 5825, 5827, 5828, 5829, 6092, 9512, 9514, 9516, 9901, 34649, 42127, 101561, 101562, 101563, 101564, 101565, 101567, 101568, 580, 582, 586, 588, 589, 596, 602, 609, 615, 633, 638, 644, 646, 2782, 2821, 2828, 2848, 4787, 4788, 7623, 7625, 7628, 7632, 19697, 19703, 29631, 29632, 29633, 29634, 29637, 29638, 29639, 54430, 54431, 54432, 54433, 54434, 54435, 54436, 54437, 54438, 54439, 54440, 54441, 10730, 10731, 10732, 10733, 10735, 10736, 10737, 10738, 10739, 28355, 28360, 28361, 28362, 2348, 11036, 11037, 11053, 11054, 11062, 11064, 20209, 20210, 20212, 46533, 47042, 47419, 70291, 70292, 70295, 70308, 70325, 96612, 96613, 96614, 96615, 96616, 96617, 96618, 96619, 96620, 96621, 96622, 96623, 96624, 96625, 96626, 96627, 96628, 96629, 96630, 96959, 96960, 96961, 96962, 96963, 96964, 96965, 96966, 96967, 96968, 96969, 96970, 96971, 96972, 96973, 96974, 96975, 96976, 96977, 96978, 96979, 96980, 96981, 111349, 116510, 205, 209, 242, 243, 279, 302, 437, 1162, 1433, 1552, 1628, 2258, 2302, 2317, 2487, 2513, 2520, 2530, 2531, 2564, 2574, 2793, 2823, 2886, 2905, 2927, 2934, 4315, 7420, 9445, 9473, 9483, 9488, 11769, 11773, 11774, 11775, 11783, 11784, 12135, 12136, 12143, 12146, 12148, 12159, 12160, 12166, 12167, 12168, 12174, 12186, 12187, 12188, 12190, 12191, 12192, 12193, 12196, 12197, 12199, 12200, 15275, 17927, 18749, 21025, 27194, 27195, 27197, 33050, 33058, 37246, 37248, 37249, 37251, 37258, 37259, 37260, 37261, 37262, 37263, 37468, 43687, 54030, 54089, 68233, 68237, 97737, 117679, 119111, 119115, 119116, 119119, 91945, 91946, 91947, 91948, 91949, 116805, 119233, 119446, 119447, 119448, 119449, 119450, 119451, 119452, 119453, 154, 157, 163, 167, 174, 175, 201, 218, 228, 235, 237, 250, 257, 298, 303, 304, 321, 331, 14658, 14659, 94562, 94563, 94564, 94565, 94567, 94568, 94569, 94570, 94571, 94572, 94573, 94575, 117453, 161, 172, 206, 215, 221, 282, 698, 728, 732, 744, 745, 780, 805, 806, 817, 827, 881, 882, 892, 894, 906, 931, 933, 940, 949, 950, 955, 956, 957, 966, 967, 988, 1004, 1005, 1013, 1017, 1024, 1025, 1028, 1038, 1684, 1686, 1687, 1689, 1698, 1702, 1707, 1708, 1709, 1710, 1715, 1716, 1719, 1723, 1724, 1728, 1730, 1734, 1741, 1742, 1754, 1755, 1759, 1761, 1765, 1780, 1783, 1784, 1788, 1793, 1794, 1809, 1810, 1817, 1818, 1819, 1820, 1824, 1827, 1828, 1830, 1832, 1838, 1844, 2783, 2784, 2785, 2790, 2791, 2796, 2797, 2801, 2804, 2805, 2808, 2812, 2816, 2819, 2820, 2822, 2824, 2825, 2830, 2831, 2832, 2837, 2838, 2839, 2843, 2844, 2846, 2854, 2856, 3315, 3420, 4417, 4419, 4424, 4433, 10064, 34758, 34759, 34772, 44861, 45804, 45846, 45868, 46501, 46894, 47061, 48062, 49623, 50102, 101109, 114808, 6131, 6132, 6134, 6139, 6142, 9725, 11895, 11908, 11909, 11910, 42241, 69440, 83566, 83567, 83568, 83569, 87204, 3478, 7103, 7985, 7986, 21735, 170, 2235, 2252, 2292, 2377, 12138, 12139, 12144, 12145, 12147, 12149, 12150, 54301, 54690, 54691, 54692, 68294, 108790, 108791, 108797, 108798, 108804, 108806, 108808, 108809, 108810, 108816, 11613, 11614, 11620, 11621, 11646, 11649, 27666, 27667, 27668, 27671, 41660, 91710, 91712, 91713, 91714, 91715, 91716, 91717, 95614, 95616, 95620, 95746, 95747, 95748, 95749, 95750, 95751, 95754, 95757, 95760, 95761, 106203, 106204, 106205, 106207, 106208, 106209, 106210, 106211, 106212, 106213, 106214, 106215, 118554, 179, 195, 315, 49707, 50484, 118432, 184, 189, 236, 238, 305, 14661, 102069, 102070, 102071, 102072, 102073, 102074, 102075, 118049, 284, 462, 545, 91875, 92850, 92851, 92852, 92853, 92854, 92855, 92856, 92858, 92859, 92861, 92862, 92864, 92866, 92867, 92868, 92872, 92883, 197, 10728, 3984, 4446, 4447, 4453, 4571, 4574, 4575, 4580, 4582, 4583, 4585, 4586, 4588, 4594, 4597, 4599, 4600, 4605, 4623, 4624, 5960, 5961, 5963, 5964, 5965, 5967, 5968, 5969, 5970, 5971, 5972, 5973, 6801, 6806, 6809, 6810, 6811, 6814, 6815, 6817, 6818, 6819, 6820, 6834, 6837, 6847, 6848, 6849, 6850, 6863, 7067, 7068, 7069, 7070, 7072, 7073, 7077, 7086, 7088, 7102, 7106, 7108, 7798, 7802, 7803, 9002, 9113, 9115, 9116, 9117, 9118, 9119, 9122, 9123, 9124, 9126, 9286, 9290, 9291, 9292, 9293, 9294, 9295, 9296, 9297, 9298, 9299, 9300, 9301, 9309, 9339, 9340, 9341, 9342, 9343, 9344, 9345, 9346, 9347, 9348, 9349, 9350, 9351, 10224, 10228, 10229, 10231, 10232, 12698, 12699, 12703, 12704, 12712, 18828, 18829, 18830, 18831, 18832, 18833, 18834, 18835, 18836, 18837, 18838, 18839, 18840, 18841, 18842, 18843, 18844, 18845, 18846, 18847, 18848, 18849, 18850, 18851, 18852, 18853, 18854, 18857, 18858, 19039, 23761, 27791, 27792, 27794, 27796, 27797, 27798, 27799, 27800, 27802, 27806, 27832, 31861, 31862, 31863, 31864, 31865, 31867, 31869, 31870, 31871, 31872, 31873, 31874, 44467, 44468, 47228, 50256, 83535, 83536, 84569, 86606, 86754, 86765, 89781, 92710, 92799, 95830, 98184, 98188, 104036, 35884, 202, 94024, 3871, 9724, 12033, 12034, 12035, 12656, 69417, 69418, 69428, 69431, 87203, 87206, 7128, 7129, 8063, 8531, 8536, 8649, 8650, 8651, 9036, 9037, 9038, 9152, 9154, 9156, 9158, 9160, 9161, 9162, 9163, 9164, 9165, 9166, 9167, 9175, 9176, 9177, 9185, 9208, 9209, 10819, 10820, 11144, 11846, 16885, 16886, 21527, 21530, 21532, 21534, 25656, 25657, 25663, 25664, 25665, 25666, 25667, 25668, 25670, 25671, 25672, 28920, 28921, 28922, 28924, 28925, 28926, 28927, 28928, 28929, 28930, 28931, 28932, 28933, 28934, 28935, 28936, 28937, 28938, 28939, 28941, 30164, 30165, 30166, 30167, 30168, 30169, 30170, 30171, 30172, 44598, 99180, 106407, 106408, 106726, 9731, 9732, 9733, 9734, 9735, 9736, 9737, 9738, 9739, 9740, 9741, 9742, 9831, 10694, 10708, 12739, 17554, 19766, 19770, 19771, 19772, 19773, 19774, 19775, 19776, 19777, 19778, 19779, 31077, 7693, 223, 94574, 255, 815, 2114, 3271, 3372, 3443, 3882, 4724, 4726, 4729, 5248, 5249, 5251, 5787, 6315, 6316, 6317, 6322, 6325, 6329, 10957, 12023, 12038, 20394, 37457, 37458, 41130, 41131, 41132, 41134, 41138, 52366, 56207, 60104, 84603, 5933, 29546, 102076, 113876, 116528, 116641, 116645, 116646, 116647, 116650, 116653, 116654, 116655, 116657, 116658, 116659, 116660, 116865, 118055, 118062, 118063, 118064, 118359, 119329, 119337, 119634, 106700, 295, 430, 92857, 92873, 92874, 92875, 92876, 92877, 92878, 94576, 94577, 94578, 94579, 94580, 94581, 110992, 119464, 308, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 5873, 5874, 5875, 5876, 5877, 5878, 5879, 5880, 5881, 5882, 5883, 5884, 5885, 5886, 5887, 5888, 5889, 6091, 9431, 9432, 9433, 31930, 31931, 31932, 31933, 31934, 31935, 31936, 31937, 31938, 31939, 31940, 31941, 3044, 3276, 3368, 3394, 3460, 3517, 4876, 4892, 5184, 5186, 5189, 5197, 5198, 5344, 5345, 6648, 7962, 7963, 7964, 7965, 7967, 7968, 7969, 7970, 7971, 7972, 7973, 7974, 7975, 7976, 7977, 7979, 7980, 7981, 7982, 7983, 7984, 7987, 7991, 7992, 7993, 11324, 11325, 11580, 11583, 11585, 11588, 11589, 11590, 11592, 11595, 11596, 11600, 11602, 11604, 11606, 11608, 12657, 13762, 13763, 13764, 13767, 13768, 13769, 13770, 13771, 13772, 13773, 13774, 13775, 13777, 13779, 13780, 13781, 13782, 13784, 14041, 14042, 14043, 14044, 14045, 14046, 14047, 14048, 14049, 14050, 14051, 14052, 14053, 14054, 21458, 21734, 21738, 21743, 21744, 21745, 69426, 69427, 87205, 87208, 87209, 87210, 87211, 87471, 118059, 381, 12368, 12369, 12370, 12371, 12373, 12375, 12376, 12377, 12378, 12379, 12381, 12382, 12383, 12384, 12385, 12386, 12387, 12388, 12389, 12390, 12391, 12392, 12393, 12394, 12395, 12396, 12398, 12399, 12400, 14523, 14524, 14972, 16672, 16673, 16676, 16677, 16683, 16686, 33969, 33970, 33972, 33976, 33977, 33978, 33980, 33981, 33983, 33984, 33985, 33987, 33991, 41193, 41194, 41196, 41198, 41199, 87021, 87022, 87023, 87025, 117154, 117155, 336, 337, 343, 382, 389, 395, 570, 617, 621, 628, 642, 648, 3274, 3487, 3722, 3723, 15202, 15203, 15214, 15216, 30286, 30347, 30351, 30355, 30359, 31821, 92287, 92293, 92294, 92301, 338, 362, 400, 569, 620, 627, 641, 647, 2842, 3400, 3724, 3727, 3730, 3731, 3733, 3735, 3738, 4017, 4018, 4020, 4022, 4029, 10051, 15204, 15206, 15210, 15211, 15212, 15218, 16690, 30287, 30290, 30293, 30297, 30301, 30305, 30311, 30315, 30319, 30322, 30326, 30330, 30334, 30338, 30342, 30346, 30350, 30354, 30358, 92270, 92271, 92272, 92273, 92274, 92278, 92285, 1224, 15765, 18109, 18120, 18124, 18125, 18127, 18129, 18155, 18158, 8584, 8588, 8590, 8591, 8592, 8593, 8594, 8595, 8597, 8599, 8600, 8601, 8602, 8603, 8604, 8605, 8607, 8608, 8609, 8610, 8626, 9223, 9225, 361, 8578, 12365, 12366, 12367, 14530, 16662, 16665, 16666, 16668, 16670, 16671, 16675, 16679, 16681, 16688, 33989, 33990, 36317, 87024, 105307, 105319, 105320, 117157, 3287, 3516, 10740, 18285, 18288, 18289, 18290, 18291, 18293, 18296, 18300, 18301, 18302, 18304, 18308, 28359, 30129, 30130, 30131, 30132, 30133, 30134, 30135, 30136, 30137, 30138, 30139, 30140, 30141, 30142, 30143, 30144, 30146, 30147, 30148, 40331, 40332, 40333, 40334, 5422, 5425, 5426, 5428, 5430, 5431, 5432, 5434, 5436, 5438, 5439, 5440, 5449, 5451, 5453, 5454, 5656, 5661, 5663, 5666, 5668, 5670, 5671, 5672, 5673, 5674, 5678, 5679, 5680, 5681, 5682, 5683, 5685, 5686, 5687, 5688, 5689, 5690, 5691, 5692, 5693, 5695, 5703, 1046, 1076, 1077, 1094, 1107, 1108, 1119, 1136, 1144, 1154, 1159, 1160, 1177, 2207, 2223, 2242, 2299, 2399, 2992, 3005, 3012, 3059, 3092, 3093, 3097, 3103, 3108, 3114, 3121, 9398, 9399, 9400, 9401, 9402, 9403, 9404, 9405, 9407, 9408, 9409, 9410, 9411, 9413, 9416, 9422, 9423, 9425, 9430, 25348, 118296, 118297, 118298, 118300, 118301, 118303, 118304, 118305, 118307, 118309, 118311, 118313, 118315, 118317, 118318, 118319, 118320, 118321, 118322, 49299, 2991, 3033, 3090, 6471, 9524, 9525, 44793, 101570, 101571, 101572, 101573, 101574, 101575, 101576, 101577, 101578, 101579, 101580, 101581, 101582, 101583, 101584, 101585, 101586, 101587, 101588, 419, 554, 759, 816, 110990, 110991, 110993, 110994, 110995, 110996, 110997, 110998, 110999, 111000, 111001, 111002, 111003, 111004, 112745, 435, 522, 6745, 6746, 6747, 6748, 6749, 6750, 6751, 6752, 6753, 6754, 6755, 6756, 12079, 12080, 12081, 12082, 12083, 12084, 97463, 482, 665, 677, 5388, 6195, 6197, 6198, 6199, 6200, 6201, 6202, 6204, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6216, 6217, 10864, 10866, 10873, 10874, 10876, 11131, 11135, 12118, 12126, 13127, 13129, 13130, 13131, 13132, 13137, 13139, 13140, 13142, 13143, 13144, 13145, 13146, 20758, 20759, 20760, 21522, 21542, 21545, 26160, 26161, 26166, 26171, 34080, 35542, 35544, 35545, 35546, 35548, 35549, 35552, 40706, 40707, 40711, 40712, 40713, 40714, 40715, 40716, 40717, 41765, 41944, 41966, 54093, 55763, 69625, 91682, 92351, 92352, 92353, 106390, 106392, 106394, 106396, 106397, 106399, 106400, 106401, 106402, 101505, 101508, 101509, 18286, 18292, 18294, 18303, 2616, 2626, 2668, 2703, 35510, 3240, 3272, 3444, 3469, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 6289, 6290, 6291, 6292, 6293, 6294, 6295, 6296, 6297, 6298, 6300, 6301, 6302, 6303, 6304, 6305, 6306, 6307, 6308, 6309, 6310, 6311, 6312, 101893, 8579, 8580, 8581, 8582, 14333, 14338, 27178, 27179, 27180, 27181, 27182, 27183, 27184, 27185, 27186, 27187, 27188, 27189, 27192, 27193, 28727, 28728, 28729, 28731, 28733, 28738, 28739, 28740, 28741, 28742, 18750, 23126, 8035, 8036, 8039, 8040, 8041, 8042, 8045, 21046, 25658, 25659, 25660, 25661, 89793, 89830, 89861, 89863, 90008, 90009, 90010, 90011, 90012, 90013, 1329, 91873, 24308, 24310, 24312, 24314, 24330, 37453, 53750, 102790, 102791, 102792, 102793, 102794, 102795, 102796, 102797, 102798, 102799, 101288, 113403, 565, 

In [ ]:
index_activityID_map = {}
for ident, idx in ident_index_map.items():
    index_activityID_map[idx] = ident_activityID_map[ident]
with open("data/probing/index_activity_map.json", "w") as f:
    json.dump(index_activityID_map, f)

index_activityID_map

{0: '32336',
 1: '32770',
 2: '33033',
 3: '33375',
 4: '34276',
 5: '35297',
 6: '35302',
 7: '35519',
 8: '36519',
 9: '37861',
 10: '39110',
 11: '40257',
 12: '40607',
 13: '40689',
 14: '40692',
 15: '40693',
 16: '40694',
 17: '41222',
 18: '41866',
 19: '41979',
 20: '41980',
 21: '41983',
 22: '41985',
 23: '41986',
 24: '41987',
 25: '42683',
 26: '42689',
 27: '43147',
 28: '44685',
 29: '45078',
 30: '45079',
 31: '45962',
 32: '46268',
 33: '49408',
 34: '49411',
 35: '49413',
 36: '50202',
 37: '51439',
 38: '51440',
 39: '51883',
 40: '51885',
 41: '51886',
 42: '51887',
 43: '53296',
 44: '53297',
 45: '53762',
 46: '53764',
 47: '53967',
 48: '53974',
 49: '54991',
 50: '55137',
 51: '55138',
 52: '57444',
 53: '57679',
 54: '58605',
 55: '60020',
 56: '60799',
 57: '60800',
 58: '60801',
 59: '61302',
 60: '62027',
 61: '62143',
 62: '62147',
 63: '62149',
 64: '62715',
 65: '62721',
 66: '64049',
 67: '66108',
 68: '66112',
 69: '66113',
 70: '66857',
 71: '67197',
 72: '67658',
 73: '67823',
 74: '69004',
 75: '69112',
 76: '69117',
 77: '70767',
 78: '71058',
 79: '71734',
 80: '72284',
 81: '72612',
 82: '72615',
 83: '72620',
 84: '74664',
 85: '74688',
 86: '74691',
 87: '74694',
 88: '75874',
 89: '75878',
 90: '76647',
 91: '76966',
 92: '78064',
 93: '78067',
 94: '81208',
 95: '81210',
 96: '81560',
 97: '82616',
 98: '82619',
 99: '83585',
 100: '84585',
 101: '84588',
 102: '85354',
 103: '85671',
 104: '86223',
 105: '86274',
 106: '86581',
 107: '86584',
 108: '87307',
 109: '88332',
 110: '88690',
 111: '89581',
 112: '89608',
 113: '89611',
 114: '89614',
 115: '90223',
 116: '90620',
 117: '92272',
 118: '92649',
 119: '93279',
 120: '94280',
 121: '94578',
 122: '94581',
 123: '95252',
 124: '95253',
 125: '95565',
 126: '96649',
 127: '97344',
 128: '97667',
 129: '97670',
 130: '98692',
 131: '98695',
 132: '99307',
 133: '100544',
 134: '101634',
 135: '102362',
 136: '102363',
 137: '103601',
 138: '103604',
 139: '103607',
 140: '104237',
 141: '104238',
 142: '105375',
 143: '105520',
 144: '105521',
 145: '105524',
 146: '105738',
 147: '106511',
 148: '106877',
 149: '107292',
 150: '107298',
 151: '107300',
 152: '107302',
 153: '107304',
 154: '107306',
 155: '107703',
 156: '107705',
 157: '108038',
 158: '108039',
 159: '108285',
 160: '108289',
 161: '108795',
 162: '108799',
 163: '108863',
 164: '108868',
 165: '109637',
 166: '110154',
 167: '110155',
 168: '110218',
 169: '110219',
 170: '110542',
 171: '110543',
 172: '111012',
 173: '111014',
 174: '111016',
 175: '111164',
 176: '111575',
 177: '111577',
 178: '111579',
 179: '111581',
 180: '111618',
 181: '111702',
 182: '112446',
 183: '112450',
 184: '112452',
 185: '113043',
 186: '113112',
 187: '113113',
 188: '113789',
 189: '113791',
 190: '113793',
 191: '114278',
 192: '114280',
 193: '114282',
 194: '114283',
 195: '114286',
 196: '114344',
 197: '114352',
 198: '114696',
 199: '115003',
 200: '115399',
 201: '115583',
 202: '115964',
 203: '116836',
 204: '116837',
 205: '116878',
 206: '116920',
 207: '116921',
 208: '116922',
 209: '117213',
 210: '117675',
 211: '118041',
 212: '118084',
 213: '118168',
 214: '118169',
 215: '118171',
 216: '118461',
 217: '118470',
 218: '118471',
 219: '118833',
 220: '119256',
 221: '119373',
 222: '119374',
 223: '119377',
 224: '119381',
 225: '119382',
 226: '119600',
 227: '119601',
 228: '120047',
 229: '120054',
 230: '120115',
 231: '120506',
 232: '120507',
 233: '120871',
 234: '121281',
 235: '121338',
 236: '121677',
 237: '121680',
 238: '121807',
 239: '121808',
 240: '121811',
 241: '122503',
 242: '122509',
 243: '122511',
 244: '122513',
 245: '122558',
 246: '122914',
 247: '122965',
 248: '123355',
 249: '123749',
 250: '124201',
 251: '124664',
 252: '124665',
 253: '125063',
 254: '125121',
 255: '125499',
 256: '125500',
 257: '125512',
 258: '125565',
 259: '125813',
 260: '126536',
 261: '126999',
 262: '127000',
 263: '127175',
 264: '127421',
 265: '127736',
 266: '127738',
 267: '127740',
 268: '128504',
 269: '128845',
 270: '128847',
 271: '128961',
 272: '129335',
 273: '129336',
 274: '129337',
 275: '129340',
 276: '129526',
 277: '130154',
 278: '130156',
 279: '130729',
 280: '130731',
 281: '130744',
 282: '130786',
 283: '130787',
 284: '130900',
 285: '131160',
 286: '131439',
 287: '131443',
 288: '131957',
 289: '131959',
 290: '131960',
 291: '132094',
 292: '132095',
 293: '132777',
 294: '132779',
 295: '133211',
 296: '133213',
 297: '133215',
 298: '133218',
 299: '133313',
 300: '133314',
 301: '133315',
 302: '133316',
 303: '133317',
 304: '133599',
 305: '133600',
 306: '133982',
 307: '133984',
 308: '134405',
 309: '134406',
 310: '134407',
 311: '134408',
 312: '134409',
 313: '134411',
 314: '134554',
 315: '134555',
 316: '134558',
 317: '134687',
 318: '134688',
 319: '134878',
 320: '135129',
 321: '135131',
 322: '135133',
 323: '135135',
 324: '135300',
 325: '135730',
 326: '135768',
 327: '136425',
 328: '136427',
 329: '136431',
 330: '136824',
 331: '136826',
 332: '137442',
 333: '137444',
 334: '137455',
 335: '138070',
 336: '138953',
 337: '138963',
 338: '138964',
 339: '139320',
 340: '139322',
 341: '139324',
 342: '139325',
 343: '139326',
 344: '139390',
 345: '139391',
 346: '139395',
 347: '139396',
 348: '139963',
 349: '140398',
 350: '140478',
 351: '140479',
 352: '141069',
 353: '141071',
 354: '141077',
 355: '141079',
 356: '141152',
 357: '141554',
 358: '141556',
 359: '141696',
 360: '141699',
 361: '141726',
 362: '141727',
 363: '141889',
 364: '141890',
 365: '142010',
 366: '142381',
 367: '142832',
 368: '142994',
 369: '142996',
 370: '143005',
 371: '143685',
 372: '144058',
 373: '144215',
 374: '144234',
 375: '144667',
 376: '145866',
 377: '145870',
 378: '145871',
 379: '145872',
 380: '147025',
 381: '147029',
 382: '147030',
 383: '148581',
 384: '148942',
 385: '149001',
 386: '149048',
 387: '150903',
 388: '157957',
 389: '158782',
 390: '159120',
 391: '159121',
 392: '159483',
 393: '160746',
 394: '161181',
 395: '161207',
 396: '161208',
 397: '161209',
 398: '161211',
 399: '161928',
 400: '161947',
 401: '162001',
 402: '164824',
 403: '165535',
 404: '166851',
 405: '166855',
 406: '170245',
 407: '171444',
 408: '173752',
 409: '173754',
 410: '174919',
 411: '175242',
 412: '175264',
 413: '175320',
 414: '178741',
 415: '178742',
 416: '178743',
 417: '178744',
 418: '178745',
 419: '178746',
 420: '178821',
 421: '178823',
 422: '180004',
 423: '180005',
 424: '180006',
 425: '180350',
 426: '182063',
 427: '182065',
 428: '182066',
 429: '182493',
 430: '182568',
 431: '182569',
 432: '182570',
 433: '183460',
 434: '183888',
 435: '184066',
 436: '184214',
 437: '184547',
 438: '184549',
 439: '185459',
 440: '185461',
 441: '185465',
 442: '187190',
 443: '187192',
 444: '189002',
 445: '189082',
 446: '189083',
 447: '189085',
 448: '189541',
 449: '189543',
 450: '189545',
 451: '189545',
 452: '189684',
 453: '189686',
 454: '189938',
 455: '190497',
 456: '191002',
 457: '191437',
 458: '191437',
 459: '191495',
 460: '191496',
 461: '191974',
 462: '192997',
 463: '193034',
 464: '193244',
 465: '193246',
 466: '194459',
 467: '194461',
 468: '194467',
 469: '195591',
 470: '195593',
 471: '195594',
 472: '195710',
 473: '196767',
 474: '198301',
 475: '198996',
 476: '198998',
 477: '199647',
 478: '200320',
 479: '200322',
 480: '200323',
 481: '200326',
 482: '200329',
 483: '200875',
 484: '200876',
 485: '201316',
 486: '201317',
 487: '202778',
 488: '202778',
 489: '202780',
 490: '203324',
 491: '203326',
 492: '203329',
 493: '203330',
 494: '203611',
 495: '203697',
 496: '203959',
 497: '204578',
 498: '204579',
 499: '204865',
 500: '205160',
 501: '205162',
 502: '205163',
 503: '205165',
 504: '205968',
 505: '205975',
 506: '206412',
 507: '206414',
 508: '206418',
 509: '206420',
 510: '207146',
 511: '208759',
 512: '209465',
 513: '209582',
 514: '209701',
 515: '209935',
 516: '209942',
 517: '210400',
 518: '210449',
 519: '211843',
 520: '213122',
 521: '213179',
 522: '213196',
 523: '213397',
 524: '213399',
 525: '214372',
 526: '214554',
 527: '214556',
 528: '215502',
 529: '215507',
 530: '215717',
 531: '216291',
 532: '216292',
 533: '216622',
 534: '216746',
 535: '217784',
 536: '217785',
 537: '217880',
 538: '218209',
 539: '218984',
 540: '218989',
 541: '219135',
 542: '220587',
 543: '220589',
 544: '220590',
 545: '220592',
 546: '221363',
 547: '221443',
 548: '221444',
 549: '221558',
 550: '221681',
 551: '222683',
 552: '225552',
 553: '226772',
 554: '226774',
 555: '226775',
 556: '226777',
 557: '226779',
 558: '226783',
 559: '228163',
 560: '228209',
 561: '228210',
 562: '228212',
 563: '229192',
 564: '230622',
 565: '230636',
 566: '230637',
 567: '230638',
 568: '230639',
 569: '230698',
 570: '231989',
 571: '233238',
 572: '233265',
 573: '233266',
 574: '233268',
 575: '233269',
 576: '233270',
 577: '233272',
 578: '234545',
 579: '234546',
 580: '234547',
 581: '234548',
 582: '235578',
 583: '235775',
 584: '238322',
 585: '238323',
 586: '238325',
 587: '239762',
 588: '241110',
 589: '241111',
 590: '242447',
 591: '242448',
 592: '242449',
 593: '242450',
 594: '243764',
 595: '246405',
 596: '246613',
 597: '246614',
 598: '246616',
 599: '247733',
 600: '247736',
 601: '247737',
 602: '247738',
 603: '247740',
 604: '249190',
 605: '249191',
 606: '249195',
 607: '249197',
 608: '249238',
 609: '249298',
 610: '249300',
 611: '250563',
 612: '250564',
 613: '250568',
 614: '250569',
 615: '250570',
 616: '250610',
 617: '250611',
 618: '250612',
 619: '251938',
 620: '251938',
 621: '251940',
 622: '251943',
 623: '251944',
 624: '251945',
 625: '251949',
 626: '252041',
 627: '253444',
 628: '254629',
 629: '254631',
 630: '254633',
 631: '254634',
 632: '254635',
 633: '254636',
 634: '256028',
 635: '256086',
 636: '256153',
 637: '256154',
 638: '256156',
 639: '257371',
 640: '257373',
 641: '257376',
 642: '257378',
 643: '257497',
 644: '257548',
 645: '257549',
 646: '257550',
 647: '257551',
 648: '257864',
 649: '258768',
 650: '258772',
 651: '258773',
 652: '258775',
 653: '258861',
 654: '258862',
 655: '258864',
 656: '260179',
 657: '260180',
 658: '260182',
 659: '262662',
 660: '262665',
 661: '262667',
 662: '262737',
 663: '262738',
 664: '263037',
 665: '265156',
 666: '265157',
 667: '265159',
 668: '265169',
 669: '265817',
 670: '265818',
 671: '266495',
 672: '266495',
 673: '266500',
 674: '266950',
 675: '267079',
 676: '267084',
 677: '267085',
 678: '267087',
 679: '267088',
 680: '268289',
 681: '268290',
 682: '268293',
 683: '269791',
 684: '269792',
 685: '270807',
 686: '270808',
 687: '271226',
 688: '271227',
 689: '271238',
 690: '271596',
 691: '272861',
 692: '272862',
 693: '273997',
 694: '274013',
 695: '274081',
 696: '274082',
 697: '274609',
 698: '274610',
 699: '275168',
 700: '275242',
 701: '275243',
 702: '276553',
 703: '276554',
 704: '276558',
 705: '276559',
 706: '276578',
 707: '276642',
 708: '276643',
 709: '278283',
 710: '278588',
 711: '278593',
 712: '278594',
 713: '278923',
 714: '280104',
 715: '280108',
 716: '280599',
 717: '281325',
 718: '283628',
 719: '284240',
 720: '284487',
 721: '284488',
 722: '284839',
 723: '284840',
 724: '284842',
 725: '284843',
 726: '284859',
 727: '284863',
 728: '284872',
 729: '284918',
 730: '284919',
 731: '285888',
 732: '285889',
 733: '285893',
 734: '285899',
 735: '286583',
 736: '286584',
 737: '287115',
 738: '287755',
 739: '287756',
 740: '288447',
 741: '288457',
 742: '288458',
 743: '289069',
 744: '289072',
 745: '289620',
 746: '289622',
 747: '289626',
 748: '289639',
 749: '290164',
 750: '292720',
 751: '293901',
 752: '293902',
 753: '294625',
 754: '294630',
 755: '294631',
 756: '294640',
 757: '294648',
 758: '295276',
 759: '295884',
 760: '295888',
 761: '295889',
 762: '296530',
 763: '296530',
 764: '296536',
 765: '296903',
 766: '297265',
 767: '297268',
 768: '297269',
 769: '299835',
 770: '299837',
 771: '299857',
 772: '300436',
 773: '300439',
 774: '300440',
 775: '301082',
 776: '301083',
 777: '301579',
 778: '301871',
 779: '301872',
 780: '302246',
 781: '302276',
 782: '302277',
 783: '303932',
 784: '303933',
 785: '304733',
 786: '304798',
 787: '305183',
 788: '305184',
 789: '305199',
 790: '306472',
 791: '306473',
 792: '306536',
 793: '307354',
 794: '307772',
 795: '307776',
 796: '307793',
 797: '307798',
 798: '308746',
 799: '308749',
 800: '308749',
 801: '308751',
 802: '308753',
 803: '308755',
 804: '308757',
 805: '308759',
 806: '308760',
 807: '309241',
 808: '309242',
 809: '309314',
 810: '309317',
 811: '309330',
 812: '309332',
 813: '309641',
 814: '310091',
 815: '310463',
 816: '310467',
 817: '311371',
 818: '311410',
 819: '312284',
 820: '312745',
 821: '312748',
 822: '312752',
 823: '312754',
 824: '312756',
 825: '312758',
 826: '313563',
 827: '314569',
 828: '314570',
 829: '314570',
 830: '314571',
 831: '314572',
 832: '314881',
 833: '315778',
 834: '316016',
 835: '316017',
 836: '316018',
 837: '316423',
 838: '316940',
 839: '316965',
 840: '316966',
 841: '316968',
 842: '316972',
 843: '316973',
 844: '316974',
 845: '316975',
 846: '316979',
 847: '316980',
 848: '316982',
 849: '316986',
 850: '316987',
 851: '316988',
 852: '316989',
 853: '316995',
 854: '318196',
 855: '318197',
 856: '318290',
 857: '318966',
 858: '320098',
 859: '320897',
 860: '321440',
 861: '321765',
 862: '321767',
 863: '321768',
 864: '321820',
 865: '321861',
 866: '321876',
 867: '321877',
 868: '321878',
 869: '321879',
 870: '322969',
 871: '323303',
 872: '323341',
 873: '323342',
 874: '323343',
 875: '323613',
 876: '324334',
 877: '324409',
 878: '324410',
 879: '324426',
 880: '324427',
 881: '324429',
 882: '324688',
 883: '325525',
 884: '325526',
 885: '326802',
 886: '326803',
 887: '326805',
 888: '327604',
 889: '327669',
 890: '328370',
 891: '328371',
 892: '328373',
 893: '328412',
 894: '328659',
 895: '328660',
 896: '329163',
 897: '329166',
 898: '329636',
 899: '329902',
 900: '330319',
 901: '330321',
 902: '330328',
 903: '330330',
 904: '330332',
 905: '330342',
 906: '331172',
 907: '331173',
 908: '331716',
 909: '332168',
 910: '332171',
 911: '333014',
 912: '333117',
 913: '333551',
 914: '333552',
 915: '333903',
 916: '334914',
 917: '334915',
 918: '334917',
 919: '335198',
 920: '335600',
 921: '336402',
 922: '336403',
 923: '337409',
 924: '337410',
 925: '337412',
 926: '338664',
 927: '338673',
 928: '338674',
 929: '338675',
 930: '338676',
 931: '340067',
 932: '340070',
 933: '340145',
 934: '340146',
 935: '340148',
 936: '340438',
 937: '340837',
 938: '341658',
 939: '342462',
 940: '343173',
 941: '343579',
 942: '343582',
 943: '343583',
 944: '345023',
 945: '345024',
 946: '345061',
 947: '345347',
 948: '346267',
 949: '346269',
 950: '346381',
 951: '346383',
 952: '347233',
 953: '347578',
 954: '347580',
 955: '348083',
 956: '348500',
 957: '348972',
 958: '348975',
 959: '348976',
 960: '348978',
 961: '349849',
 962: '349857',
 963: '351310',
 964: '351311',
 965: '351337',
 966: '351747',
 967: '352155',
 968: '352638',
 969: '353093',
 970: '353111',
 971: '353113',
 972: '353115',
 973: '353633',
 974: '354673',
 975: '354675',
 976: '354790',
 977: '354795',
 978: '355097',
 979: '355098',
 980: '355668',
 981: '355669',
 982: '356125',
 983: '356129',
 984: '357621',
 985: '357624',
 986: '357628',
 987: '358523',
 988: '358903',
 989: '358905',
 990: '358906',
 991: '358907',
 992: '359967',
 993: '359969',
 994: '359970',
 995: '360291',
 996: '360293',
 997: '360294',
 998: '360720',
 999: '360724',
 ...}

In [38]:
print(os.getcwd())
templates_dir = "../kinodata-3D/data/templates.csv"
ref_dir = "data/probing/human_kinases_and_chembl_targets.chembl_33.csv"
activity_100 = "data/probing/activities-chembl33-sample100_v0.5.csv"
chembl_activity = "data/probing/activities-chembl33_v0.5.csv"
egfr_activity = "data/probing/EGFR-activities-chembl33.csv"
reference_df = pd.read_csv(ref_dir)
egfr_activity = pd.read_csv(egfr_activity)
activity_100 = pd.read_csv(activity_100)
chembl_activity = pd.read_csv(chembl_activity)

/home/fatemeh/thesis/kinodata-3D-affinity-prediction

In [23]:
data[0]

HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='C1CCC(CC2CCC(CC3CCCC4CCCCC43)CC2)CC1',
  activity_type='pIC50',
  ident=[1],
  smiles='c1ccc(Oc2ccc(Nc3ncnc4ccccc34)cc2)cc1',
  ligand={
    z=[24],
    x=[24, 12],
    pos=[24, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[676, 12],
    z=[676],
    pos=[676, 3],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 54],
    edge_attr=[54, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1362],
    edge_attr=[1362, 4],
  }
)

In [39]:
chembl_activity.head()

,Unnamed: 0,activities.activity_id,assays.chembl_id,target_dictionary.chembl_id,molecule_dictionary.chembl_id,molecule_dictionary.max_phase,activities.standard_type,activities.standard_value,activities.standard_units,compound_structures.canonical_smiles,compound_structures.standard_inchi,component_sequences.sequence,assays.confidence_score,docs.chembl_id,docs.year,docs.authors,UniprotID
0,96698,16291323,CHEMBL3705523,CHEMBL2973,CHEMBL3666724,NaN,pIC50,14.096910,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C31H33N7O3/c1-2-4-29(40)33-22-6-3-5-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
1,94326,16264754,CHEMBL3705523,CHEMBL2973,CHEMBL3666728,NaN,pIC50,14.000000,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C34H40N8O3/c1-5-7-32(43)36-24-9-6-8-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
2,98119,16306943,CHEMBL3705523,CHEMBL2973,CHEMBL1968705,NaN,pIC50,14.000000,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C31H33N7O2/c1-2-6-29(39)33-23-8-5-7-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
3,101161,16340050,CHEMBL3705523,CHEMBL2973,CHEMBL1997433,NaN,pIC50,13.958607,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C28H28N6O3/c1-3-5-26(35)30-20-7-4-6-1...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
4,101541,16344107,CHEMBL3705523,CHEMBL2973,CHEMBL3666722,NaN,pIC50,13.920819,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C32H36N8O2/c1-3-5-30(41)34-24-7-4-6-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116

In [10]:
egfr_activity.head()

,Unnamed: 0.1,Unnamed: 0,activities.activity_id,assays.chembl_id,target_dictionary.chembl_id,molecule_dictionary.chembl_id,molecule_dictionary.max_phase,activities.standard_type,activities.standard_value,activities.standard_units,compound_structures.canonical_smiles,compound_structures.standard_inchi,component_sequences.sequence,assays.confidence_score,docs.chembl_id,docs.year,docs.authors,UniprotID
0,57,7654,1044894,CHEMBL683040,CHEMBL203,CHEMBL63786,NaN,pIC50,11.522879,nM,Brc1cccc(Nc2ncnc3cc4ccccc4cc23)c1,InChI=1S/C18H12BrN3/c19-14-6-3-7-15(10-14)22-1...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,9,CHEMBL1129035,1996.0,"Rewcastle GW, Palmer BD, Bridges AJ, Showalter...",P00533
1,107,1064,191437,CHEMBL677389,CHEMBL203,CHEMBL35820,NaN,pIC50,11.221849,nM,CCOc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OCC,InChI=1S/C18H18BrN3O2/c1-3-23-16-9-14-15(10-17...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,8,CHEMBL1130030,1997.0,"Palmer BD, Trumpp-Kallmeyer S, Fry DW, Nelson ...",P00533
2,108,7949,1082447,CHEMBL680021,CHEMBL203,CHEMBL53711,NaN,pIC50,11.221849,nM,CN(C)c1cc2c(Nc3cccc(Br)c3)ncnc2cn1,InChI=1S/C15H14BrN5/c1-21(2)14-7-12-13(8-17-14...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,8,CHEMBL1129564,1996.0,"Rewcastle GW, Palmer BD, Thompson AM, Bridges ...",P00533
3,150,2936,428391,CHEMBL679944,CHEMBL203,CHEMBL66031,NaN,pIC50,11.096910,nM,Brc1cccc(Nc2ncnc3cc4[nH]cnc4cc23)c1,InChI=1S/C15H10BrN5/c16-9-2-1-3-10(4-9)21-15-1...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,8,CHEMBL1132555,1999.0,"Showalter HD, Bridges AJ, Zhou H, Sercel AD, M...",P00533
4,151,2647,400160,CHEMBL679944,CHEMBL203,CHEMBL53753,NaN,pIC50,11.096910,nM,CNc1cc2c(Nc3cccc(Br)c3)ncnc2cn1,InChI=1S/C14H12BrN5/c1-16-13-6-11-12(7-17-13)1...,MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFED...,8,CHEMBL1132555,1999.0,"Showalter HD, Bridges AJ, Zhou H, Sercel AD, M...",P00533

In [6]:
activity_100.head(10)

,Unnamed: 0,activities.activity_id,assays.chembl_id,target_dictionary.chembl_id,molecule_dictionary.chembl_id,molecule_dictionary.max_phase,activities.standard_type,activities.standard_value,activities.standard_units,compound_structures.canonical_smiles,compound_structures.standard_inchi,component_sequences.sequence,assays.confidence_score,docs.chembl_id,docs.year,docs.authors,UniprotID
0,96698,16291323,CHEMBL3705523,CHEMBL2973,CHEMBL3666724,NaN,pIC50,14.096910,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C31H33N7O3/c1-2-4-29(40)33-22-6-3-5-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
1,94326,16264754,CHEMBL3705523,CHEMBL2973,CHEMBL3666728,NaN,pIC50,14.000000,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C34H40N8O3/c1-5-7-32(43)36-24-9-6-8-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
2,98119,16306943,CHEMBL3705523,CHEMBL2973,CHEMBL1968705,NaN,pIC50,14.000000,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C31H33N7O2/c1-2-6-29(39)33-23-8-5-7-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
3,101161,16340050,CHEMBL3705523,CHEMBL2973,CHEMBL1997433,NaN,pIC50,13.958607,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C28H28N6O3/c1-3-5-26(35)30-20-7-4-6-1...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
4,101541,16344107,CHEMBL3705523,CHEMBL2973,CHEMBL3666722,NaN,pIC50,13.920819,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C32H36N8O2/c1-3-5-30(41)34-24-7-4-6-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
5,96324,16287186,CHEMBL3705523,CHEMBL2973,CHEMBL3666721,NaN,pIC50,13.920819,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C32H35N7O2/c1-2-7-30(40)34-24-9-6-8-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
6,99433,16320578,CHEMBL3705523,CHEMBL2973,CHEMBL3666727,NaN,pIC50,13.853872,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C33H38N8O3/c1-4-6-31(42)35-24-8-5-7-2...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
7,95350,16276310,CHEMBL3705523,CHEMBL2973,CHEMBL3666758,NaN,pIC50,13.619789,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C29H30N6O4/c1-4-6-27(36)31-20-8-5-7-1...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
8,96706,16291435,CHEMBL3705523,CHEMBL2973,CHEMBL3666756,NaN,pIC50,13.537602,nM,CCCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3ccc...,InChI=1S/C26H24N6O/c1-2-3-11-24(33)28-19-8-6-7...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116
9,100633,16334330,CHEMBL3705523,CHEMBL2973,CHEMBL3666726,NaN,pIC50,13.537602,nM,CCCC(=O)Nc1cccc(-c2nc(Nc3ccc4[nH]ncc4c3)c3cc(O...,InChI=1S/C29H30N6O4/c1-4-6-27(36)31-20-8-5-7-1...,MSRPPPTGKMPGAPETAPGDGAGASRQRKLEALIRDPRSPINVESL...,9,CHEMBL3639077,2014.0,NaN,O75116

### Check PyGs
1. Randomely select 100 Kinodata idents? or it's better to just check the first 100 
What to check for exactly?
    ``` 
    data.smiles == egfr_activity['compound_structures.canonical_smiles']
    data.y == egfr_activity['activities.activity_value'] 
    ```

In [18]:
data

KinodataDocked(41238)

In [31]:
egfr_activity[egfr_activity['compound_structures.canonical_smiles'] == 'Brc1cccc(Nc2ncnc3cc4ccccc4cc23)c1']['compound_structures.canonical_smiles']

0    Brc1cccc(Nc2ncnc3cc4ccccc4cc23)c1
Name: compound_structures.canonical_smiles, dtype: object

In [68]:
type(chembl_activity[chembl_activity['activities.activity_id'] == 2616278 ]['activities.standard_value'].values[0])

numpy.float64

In [43]:
print(min(egfr_activity['activities.activity_id'].values))

32260

In [105]:
import random
# randome_idents = random.sample(list(ident_index_map.keys()), 100)
n = len(data)

def check_info(graph: KinodataDocked,
                activity_ref: pd.DataFrame,
                id: str,
                ref_id_name: str = "activities.activity_id",
                ref_smiles_name: str = "compound_structures.canonical_smiles",
                ref_activity_value: str = "activities.standard_value"
                ):
    id = int(id)
    if id not in activity_ref[ref_id_name].values:
        # print(f"ID {id} not found in the reference activity dataframe")
        return False
    
    # check SMILES
    # ref_smiles = activty_ref[activty_ref[ref_id_name] == id][ref_smiles_name].values[0] # series to value
    # print(f"Ref SMILES: {ref_smiles}")
    # print(f"Graph SMILES: {graph.smiles}")
    # assert graph.smiles == ref_smiles, f"SMILES do not match for Kinodata {graph.ident}"

    # check activity_id
    try:
        ref_activity = activity_ref[activity_ref[ref_id_name] == id][ref_activity_value].values[0]
    except IndexError:
        print(f"activity not found in the reference activity dataframe")
        return False
    # assert graph.y.item() == ref_activity, f"Activity ID do not match for Kinodata {graph.ident}"
    print(f"PyG activity: {graph.y.item():.2f}, chEMBL activity: {ref_activity:.2f}")
    if graph.y.item() != ref_activity:
        return False


    return True

# Check k random graphs
k = 10
not_found = []
found = []
for i in random.sample(range(n+1), k):
# for i in range(10):
    graph = data[i]
    # activity_id = ident_activityID_map[graph.ident.item()]
    if not check_info(graph, activity_ref=chembl_activity, id=index_activityID_map[i]):
        not_found.append(index_activityID_map[i])
    else:
        found.append(index_activityID_map[i])

print(f"Found {len(found)} IDs: {found}")
print(f"Not found {len(not_found)} IDs: {not_found}")

PyG activity: 8.26, chEMBL activity: 3.82
PyG activity: 8.84, chEMBL activity: 5.64
PyG activity: 7.77, chEMBL activity: 7.13
PyG activity: 3.12, chEMBL activity: 7.41
PyG activity: 5.89, chEMBL activity: 6.05
PyG activity: 6.12, chEMBL activity: 8.15
PyG activity: 5.94, chEMBL activity: 5.81
PyG activity: 4.54, chEMBL activity: 5.89
PyG activity: 6.58, chEMBL activity: 8.96
PyG activity: 7.89, chEMBL activity: 7.30
Found 0 IDs: []
Not found 10 IDs: ['459505', '3131720', '189082', '2921949', '2159822', '1149523', '2167616', '7576481', '12177074', '1467281']

In [ ]:
print(data[0].ident.item())
print(data[0])

20
HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='C1CCC(CC2CCC(CC3CCCC4CCCCC43)CC2)CC1',
  activity_type='pIC50',
  ident=[1],
  smiles='c1ccc(Oc2ccc(Nc3ncnc4ccccc34)cc2)cc1',
  ligand={
    z=[24],
    x=[24, 12],
    pos=[24, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[676, 12],
    z=[676],
    pos=[676, 3],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 54],
    edge_attr=[54, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1362],
    edge_attr=[1362, 4],
  }
)

# Load

In [12]:
mini_data = torch.load("data/probing/100subset_data.pt", weights_only=False)

In [ ]:
mini_loader = DataLoader(
        mini_data,
        batch_size=20,
    )

### trying even smaller

In [ ]:
nini_data = mini_data[:10]
torch.save(nini_data, "data/probing/10subset_data.pt")

In [3]:
nini_data  = torch.load("data/probing/10subset_data.pt", weights_only=False)
nini_loader = DataLoader(
        nini_data,
        batch_size=20,
    )

In [18]:
nini_data[0]

HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='C1CCC(CC2CCC(CC3CCCC4CCCCC43)CC2)CC1',
  activity_type='pIC50',
  ident=[1],
  smiles='c1ccc(Oc2ccc(Nc3ncnc4ccccc34)cc2)cc1',
  ligand={
    z=[24],
    x=[24, 12],
    pos=[24, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[676, 12],
    z=[676],
    pos=[676, 3],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 54],
    edge_attr=[54, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1362],
    edge_attr=[1362, 4],
  }
)

In [5]:
with open("data/probing/10_ident_to_idx.json", "w") as f:
    json.dump(nini_data.ident_index_map(), f)

### trying one graph

In [5]:
a_complex = torch.load("data/probing/a_complex.pt", weights_only=False)

Synthesized batch tensor

In [5]:
a_complex[NodeType.Complex].batch = torch.zeros(a_complex[NodeType.Complex].x.shape[0]).type(torch.int64)
a_complex

HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='C1CCC(CC2CCC(CC3CCCC4CCCCC43)CC2)CC1',
  activity_type='pIC50',
  ident=[1],
  smiles='c1ccc(Oc2ccc(Nc3ncnc4ccccc34)cc2)cc1',
  ligand={
    z=[24],
    x=[24, 12],
    pos=[24, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[676, 12],
    z=[676],
    pos=[676, 3],
    batch=[676],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 54],
    edge_attr=[54, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1362],
    edge_attr=[1362, 4],
  }
)

Data module, but crashes

In [5]:
data_module = make_kinodata_module(
    cfg.get("data", "training").update(
        dict(
            batch_size=32,
            split_type="scaffold-k-fold",
            filter_rmsd_max_value=2.0,
            split_index=0,
        )
    ),
    transforms=[TransformToComplexGraph(remove_heterogeneous_representation=False)],
)

:

# Loading the model

In [6]:
print(Path.cwd())

/home/fatemeh/thesis/kinodata-3D-affinity-prediction

In [6]:
model_dir = Path("models")
# print(model_dir)
assert model_dir.exists()

def path_to_model(rmsd_threshold: int, split_type: str, split_fold: int, model_type: str) -> Path:
    p = model_dir / f"rmsd_cutoff_{rmsd_threshold}" / split_type / str(split_fold) / model_type
    if not p.exists():
        p.mkdir(parents=True)
    return p

cgnn_3d_path = path_to_model(rmsd_threshold=2, split_type="scaffold-k-fold", split_fold=0, model_type="CGNN-3D")
cgnn_3d_ckpt = list(cgnn_3d_path.glob("**/*.ckpt"))[0]
# print(model_ckpt)
cgnn_3d_config = cgnn_3d_path / "config.json"
# print(model_config)

In [7]:
def load_wandb_config(
    config_file: Path
) -> dict[str, Any]:
    with open(config_file, "r") as f_config:
        config = json.load(f_config)
    config = {str(key): value["value"] for key, value in config.items()}
    return config

In [8]:
config = cfg.Config(load_wandb_config(cgnn_3d_config))
cgnn_3d = make_complex_transformer(config)

In [9]:
model_cls = {
    # "DTI": make_dti_baseline,
    # "CGNN": make_complex_transformer,
    "CGNN-3D": make_complex_transformer
}

def load_from_checkpoint(model: RegressionModel, model_ckpt: str) -> RegressionModel:
    ckp = torch.load(model_ckpt, map_location="cpu")
    assert isinstance(model, RegressionModel)
    model.load_state_dict(ckp["state_dict"])
    return model

In [10]:
cgnn_3d_loaded = load_from_checkpoint(model = cgnn_3d, model_ckpt=cgnn_3d_ckpt)
cgnn_3d_loaded.train(False)

ComplexTransformer(
  (criterion): MSELoss()
  (act): SiLU()
  (interaction_module): CombinedInteractions(
    (interactions): ModuleList(
      (0): CovalentInteractions(
        (act): SiLU()
        (lin): Linear(in_features=4, out_features=256, bias=True)
      )
      (1): StructuralInteractions(
        (act): SiLU()
        (distance_embedding): GaussianDistEmbedding()
        (lin): Linear(in_features=256, out_features=256, bias=False)
      )
    )
    (act): SiLU()
  )
  (atomic_num_embedding): Embedding(100, 256)
  (lin_atom_features): Linear(in_features=12, out_features=256, bias=True)
  (attention_blocks): ModuleList(
    (0-2): 3 x SPAB(
      (attention): SparseAttention(
        (lin_query): Linear(in_features=256, out_features=256, bias=False)
        (lin_key_value): Linear(in_features=256, out_features=512, bias=False)
        (lin_bias): Linear(in_features=256, out_features=512, bias=False)
        (lin_out): Linear(in_features=256, out_features=256, bias=False)
      )
      (ln1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff): Sequential(
        (0): Linear(in_features=256, out_features=256, bias=True)
        (1): SiLU()
        (2): Linear(in_features=256, out_features=256, bias=True)
      )
      (ln2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (ff_edge): Sequential(
        (0): Linear(in_features=4, out_features=256, bias=True)
        (1): SiLU()
        (2): Linear(in_features=256, out_features=256, bias=True)
      )
      (ln3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
  (aggr): SoftmaxAggregation(learn=True)
  (out): Sequential(
    (0): Dropout(p=0, inplace=False)
    (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): SiLU()
    )
    (3): Linear(in_features=256, out_features=1, bias=True)
  )
)

In [12]:
config

Config(lr=0.0001, act=silu, ln1=True, ln2=True, ln3=True, seed=420, optim=adamw, epochs=300, k_fold=5, min_lr=1e-06, dropout=0, dry_run=False, loss_type=mse, lr_factor=0.9, num_heads=4, use_bonds=True, batch_size=42, data_split=None, edge_types=[['ligand', 'intraacts', 'ligand'], ['ligand', 'interacts', 'pocket'], ['pocket', 'interacts', 'ligand']], graph_norm=False, node_types=['complex'], split_type=scaffold-k-fold, accelerator=gpu, lr_patience=8, num_workers=32, split_index=0, weight_decay=3e-06, edge_attr_size=4, need_distances=False, clip_grad_value=None, hidden_channels=256, remove_hydrogen=True, interaction_modes=['covalent', 'structural'], max_num_neighbors=16, add_docking_scores=False, interaction_radius=6, num_attention_blocks=3, num_residue_features=6, add_artificial_decoys=False, filter_rmsd_max_value=2, accumulate_grad_batches=3, early_stopping_patience=24, additional_atom_features=False, perturb_ligand_positions=0, perturb_pocket_positions=0, perturb_complex_positions=0.1, residue_interaction_radius=12)

### Predict

In [10]:
import numpy as np
from kinodata.model.regression import RegressionModel, cat_many
from torch_geometric.loader import DataLoader
from pytorch_lightning import Trainer
import pandas as pd


def predict_df(
    model: RegressionModel,
    loader: DataLoader,
    trainer: Trainer | None = None,
    ckpt_path: str | None = "best",
) -> pd.DataFrame:
    if trainer is None:
        trainer = Trainer()
    dict_list = trainer.predict(model, loader, ckpt_path=ckpt_path)
    return pd.DataFrame(
        {key: np.array(value) for key, value in cat_many(dict_list).items()}
    )

Forward pass for only one

In [18]:
a_pred = cgnn_3d_loaded(a_complex)[0][0].item()	
a_pred

6.6271257400512695

Forward pass for nini

In [9]:
nini_dataset = next(iter(nini_loader))
nini_dataset

HeteroDataBatch(
  y=[10],
  docking_score=[10],
  posit_prob=[10],
  predicted_rmsd=[10],
  pocket_sequence=[10],
  scaffold=[10],
  activity_type=[10],
  ident=[10],
  smiles=[10],
  ligand={
    z=[262],
    x=[262, 12],
    pos=[262, 3],
    batch=[262],
    ptr=[11],
  },
  pocket={
    z=[6520],
    x=[6520, 12],
    pos=[6520, 3],
    batch=[6520],
    ptr=[11],
  },
  pocket_residue={
    x=[850, 23],
    batch=[850],
    ptr=[11],
  },
  complex={
    x=[6782, 12],
    z=[6782],
    pos=[6782, 3],
    batch=[6782],
    ptr=[11],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 582],
    edge_attr=[582, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 13080],
    edge_attr=[13080, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 13662],
    edge_attr=[13662, 4],
  }
)

In [ ]:
nini_dataset

AttributeError: 'HeteroDataBatch' has no attribute 'pocket'

In [24]:
out_graphs, intermediate_node_reprs, intermediate_edge_reprs = cgnn_3d_loaded(nini_dataset)

In [29]:
torch.save(intermediate_edge_reprs, "data/probing/10subset_intermediate_edge_reprs.pt")
torch.save(intermediate_node_reprs, "data/probing/10subset_intermediate_node_reprs.pt")

Forward pass for mini

In [ ]:
# from kinodata.training.predict import predict_df
df_mini_data = predict_df(cgnn_3d, mini_loader, ckpt_path = cgnn_3d_ckpt)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/fatemeh/miniconda3/envs/kinodata3d/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:75: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
Restoring states from the checkpoint path at models/rmsd_cutoff_2/scaffold-k-fold/0/CGNN-3D/model.ckpt
Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v2.2.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint models/rmsd_cutoff_2/scaffold-k-fold/0/CGNN-3D/model.ckpt`
Loaded model weights from the checkpoint at models/rmsd_cutoff_2/scaffold-k-fold/0/CGNN-3D/model.ckpt
/home/fatemeh/miniconda3/envs/kinodata3d/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:441: The 'predict_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Predicting DataLoader 0: 100%|██████████| 5/5 [00:30<00:00,  0.16it/s]

In [ ]:
df_mini_data

        pred    target
0   6.627124  5.565431
1   6.645761  5.327902
2   6.273721  5.853872
3   6.421379  6.214670
4   6.219614  7.335480
..       ...       ...
95  7.735117  8.958607
96  6.659325  6.121478
97  7.646967  6.856985
98  7.124436  6.357535
99  7.789174  6.990650

[100 rows x 2 columns]

In [ ]:
df_mini_data.to_pickle("/data/probing/y_prob_exp_1.pkl")

# Load from here

In [4]:
print(os.getcwd())

/home/fatemeh/thesis/kinodata-3D-affinity-prediction

In [8]:
num_reprs = config.get("num_attention_blocks")
# prob_dir = "data/probing/"
# prob_dir = "data/probing/one_complex/"

Loading for nini

In [11]:
intermediate_node_reprs = torch.load("data/probing/10subset_intermediate_node_reprs.pt", weights_only=False)
intermediate_edge_reprs = torch.load("data/probing/10subset_intermediate_edge_reprs.pt", weights_only=False)

Node

In [12]:
l1_node_reps, l1_batch = intermediate_node_reprs['layer_1']
l2_node_reps, l2_batch = intermediate_node_reprs['layer_2']
l3_node_reps, l3_batch = intermediate_node_reprs['layer_3']
print(l1_node_reps.shape, l1_batch.shape)
print(l2_node_reps.shape, l2_batch.shape)
print(l3_node_reps.shape, l3_batch.shape)

torch.Size([6782, 256]) torch.Size([6782])
torch.Size([6782, 256]) torch.Size([6782])
torch.Size([6782, 256]) torch.Size([6782])

Which complex in the batch each node belongs to

In [19]:
l1_batch.numpy()

array([0, 0, 0, ..., 9, 9, 9])

Embedding of node 0

In [23]:
l1_node_reps[0]

tensor([ 0.0200,  0.7585, -0.3484,  0.3835, -0.3097, -0.2597, -0.6393, -0.5757,
        -0.5918, -0.5617, -0.8123, -0.2459, -0.6008, -0.6400,  0.3363, -0.2215,
         0.4644, -0.9577, -0.0062,  3.0970,  0.4022,  2.0260,  1.5093, -1.1255,
        -0.8451,  1.6359, -1.0697, -0.5283, -0.5975,  2.0577,  1.8443, -0.1801,
        -0.8154, -0.2125, -0.4587, -0.6479, -0.2282, -0.5257,  0.4545,  0.3910,
         1.0702, -0.1959, -0.1889,  0.6674, -0.0415,  1.0018,  0.4644,  0.0127,
        -0.7523, -0.8671,  3.8887, -1.0138, -0.7219,  0.2256, -0.1281,  0.9337,
        -0.5764, -0.1649, -0.3038,  1.9540, -0.2194,  0.6843, -0.2527, -0.2123,
         0.2200,  0.3960, -1.0390, -0.3688, -0.3258,  0.1840, -0.4090, -0.7660,
        -0.3424, -0.6368, -0.7595, -0.5778, -0.5155,  0.7241, -0.9008,  0.0341,
        -0.1755, -0.8062, -0.7101, -0.6342, -0.3076, -0.2067,  0.5957,  0.7663,
        -0.8358,  2.3242, -1.0362, -0.1427, -0.8269,  0.1739,  0.3451, -0.4920,
        -0.6373, -1.0586, -1.3569,  1.7413, -0.7719, -0.5242, -1.0609, -0.7794,
         2.8139, -0.8093,  0.6727, -0.4788, -1.2638,  0.4414, -0.5800, -0.6914,
        -1.2210, -0.4322,  0.2623, -0.2620, -0.6961,  2.1989, -1.0133, -0.7789,
        -0.7903, -0.5088, -0.2097,  0.2227,  0.0792, -0.1202,  1.2201,  0.4797,
        -1.4452,  0.4428, -0.8236,  1.2581, -0.5156, -0.3950,  0.0783,  1.6324,
        -0.4709, -0.6144, -0.2396,  0.3470,  0.6493,  1.1238, -0.1545, -0.7587,
        -0.6550, -0.5863, -0.3100, -0.6808,  0.7047, -1.1123, -0.4614, -0.2170,
        -0.8264, -0.8242, -0.2535, -0.7195, -0.0999, -0.1739,  0.4853, -0.1979,
         0.9768,  0.3975,  2.7678,  0.4781, -0.6918, -0.0943, -0.1559, -1.0261,
        -0.3680, -1.1335, -0.4881,  0.0621, -0.4826, -0.1940, -0.6049, -0.5015,
        -0.2853,  2.4320, -0.9457,  0.8862, -0.2430, -1.0310, -0.4712, -0.3731,
        -0.8691, -0.1721, -0.2618, -0.8359, -0.3457,  0.5056,  3.4998,  0.3362,
        -0.4088,  0.7663,  0.5078,  0.0768,  0.1101,  0.2253, -0.6205, -0.5707,
        -0.1100,  2.0119,  1.1457, -0.3273, -0.2888, -0.2119, -0.1236, -0.9870,
        -1.1357,  0.8218, -0.2147, -0.2530,  0.1222, -0.1736, -0.8994, -0.5376,
         0.4939, -1.2565, -1.0206, -0.2304, -0.0563, -0.5604, -0.3004,  0.9709,
        -0.6609,  1.0959, -0.3949, -0.1269,  4.8048, -0.2019, -0.5315, -0.3649,
         2.2456,  1.6062, -0.2327,  2.9323,  2.8282,  0.9787,  0.0290, -0.1265,
        -0.3776,  2.8540,  0.6105,  2.6954, -0.5437, -0.7471, -1.1259,  0.3550,
        -0.6375, -0.8080, -1.0973, -0.8393,  0.3667, -0.3525,  0.7073, -0.2922])

Edge

In [13]:
l1_edge_reps, l1_edge_index = intermediate_edge_reprs['layer_1']
print(l1_edge_reps.shape, l1_edge_index.shape)

torch.Size([113774, 256]) torch.Size([2, 113774])

In [32]:
# graf_edge_index, graf_edge = subgraph(complex_indices, edge_index = intermediate_edge_reprs[f"layer_{i+1}"][1], edge_attr = intermediate_edge_reprs[f"layer_{i+1}"][0])

- First row: source node
- Second row: destination node

In [21]:
l1_edge_index

tensor([[   0,    0,    0,  ..., 6781, 6781, 6781],
        [   0,    1,    2,  ..., 6778, 6779, 6781]])

### Unbatch the representations

In [14]:
from torch_geometric.utils import unbatch_edge_index, unbatch, subgraph

# separating the batched node and edge representations
unbatched_nodes = unbatch(l1_node_reps, batch=l1_batch)
unbatched_edge_indices = unbatch_edge_index(l1_edge_index, batch=l1_batch)
unbatched_edges = [subgraph(torch.where(l1_batch == i)[0], edge_index = l1_edge_index, edge_attr = l1_edge_reps)[1] for i in range(l1_batch.max().item() + 1)]

print(unbatched_nodes[0].shape)
print(unbatched_edge_indices[0].shape)
print(unbatched_edges[0].shape)

torch.Size([676, 256])
torch.Size([2, 11340])
torch.Size([11340, 256])

Need to unbatch edge reprs as well
Then, extract the ident of that complex, and create another object that holds the hidden representations? or, just record the necessary information needed for the target molecule property?
Could that be the number of hydrogen atoms?

In [ ]:
# To check if the subgraphs inside the batch are correct, through their edge indices
for i, (nodes, edge_indices) in enumerate(zip(unbatched_nodes, unbatched_edge_indices)):
    print(nodes.shape, edge_indices.shape)
    # complex_indices = torch.where(nini_dataset[NodeType.Complex].batch == i)[0] 
    embed_indices = torch.where(l1_batch == i)[0]
    embed_edge_index, embed_edge = subgraph(embed_indices, edge_index = l1_edge_index, edge_attr = l1_edge_reps)
    
    # whether both tensors have the same shape and values:
    # assert torch.equal(edge_indices, embed_edge_index)
    print(torch.equal(edge_indices, embed_edge_index)) # why thet are not the same?
    
    # src_graph = nini_loader.dataset[i]
    # src_graph.probe = {'node': nodes, 'edge_attr': embed_edge, 'edge_index': edge_indices}
    # nini_loader.dataset[i] = src_graph

torch.Size([676, 256]) torch.Size([2, 11340])
True
torch.Size([678, 256]) torch.Size([2, 11374])
False
torch.Size([677, 256]) torch.Size([2, 11357])
False
torch.Size([677, 256]) torch.Size([2, 11357])
False
torch.Size([677, 256]) torch.Size([2, 11357])
False
torch.Size([678, 256]) torch.Size([2, 11374])
False
torch.Size([681, 256]) torch.Size([2, 11425])
False
torch.Size([680, 256]) torch.Size([2, 11408])
False
torch.Size([678, 256]) torch.Size([2, 11374])
False
torch.Size([680, 256]) torch.Size([2, 11408])
False

In [16]:
from torch_geometric.utils import subgraph

sample = subgraph(subset=unbatched_nodes[7], edge_index=l1_edge_index, edge_attr=l1_edge_reps)
sample

IndexError: tensors used as indices must be long, int, byte or bool tensors

Match batch

In [70]:
batch_tensor = nini_dataset[NodeType.Complex].batch
batch_tensor

tensor([0, 0, 0,  ..., 9, 9, 9])

In [86]:
complex_graph = nini_dataset[7]
complex_graph

HeteroData(
  y=[1],
  docking_score=[1],
  posit_prob=[1],
  predicted_rmsd=[1],
  pocket_sequence='KPLGRGAFGQVIEVAVKMLALMSELKILIHIGLNVVNLLGAMVIVEFCKFGNLSTYLRSFLASRKCIHRDLAARNILLICDFGLA',
  scaffold='CC(CC1CCC(C2CCCCC2)CC1)C1CCCC1CCC1CCCCC1',
  activity_type='pIC50',
  ident=[1],
  smiles='O=C(Nc1ccc(-c2ccccc2)cc1)c1scnc1CCc1ccncc1',
  ligand={
    z=[28],
    x=[28, 12],
    pos=[28, 3],
  },
  pocket={
    z=[652],
    x=[652, 12],
    pos=[652, 3],
  },
  pocket_residue={ x=[85, 23] },
  complex={
    x=[680, 12],
    z=[680],
    pos=[680, 3],
  },
  (ligand, bond, ligand)={
    edge_index=[2, 62],
    edge_attr=[62, 4],
  },
  (pocket, bond, pocket)={
    edge_index=[2, 1308],
    edge_attr=[1308, 4],
  },
  (complex, bond, complex)={
    edge_index=[2, 1370],
    edge_attr=[1370, 4],
  }
)

In [ ]:
where = torch.where(batch_tensor == l1_batch[7])

In [18]:
from torch_geometric.utils import subgraph

mask = nini_dataset[NodeType.Complex].batch == 7
print(mask.shape)
node_indices = mask.nonzero().squeeze()
graf = subgraph(node_indices, edge_index = l1_edge_index, edge_attr = l1_edge_reps)
graf

torch.Size([6782])

(tensor([[4744, 4744, 4744,  ..., 5423, 5423, 5423],
         [4744, 4745, 4746,  ..., 5421, 5422, 5423]]),
 tensor([[ 1.3687,  0.9872,  1.6187,  ...,  0.5174, -0.8656,  0.0251],
         [-0.9179, -0.9602,  1.2176,  ...,  1.4060, -0.9959, -1.5741],
         [-0.2900,  0.1892,  0.8599,  ...,  0.2710, -0.8691, -0.8715],
         ...,
         [ 0.7387,  0.1890,  0.3719,  ..., -1.1737, -2.8108, -0.3334],
         [ 0.5311,  0.1831,  0.2935,  ..., -0.9659, -2.4069, -0.3310],
         [ 1.2902,  1.0573,  1.5724,  ..., -0.1667, -1.9189, -0.6477]]))

In [24]:
graf[0].shape

torch.Size([2, 11408])

In [ ]:
nini_dataset[NodeType.Complex].batch.numpy()

tensor([0, 0, 0,  ..., 9, 9, 9])

Loading for mini

In [3]:
with open("data/probing/ident_to_idx.json", "r") as f:
    ident_to_idx = json.load(f)

In [ ]:
prob_dir = "data/probing/one_complex/"
edge_indices = []
edge_reprs = []
node_reprs = []


for i in range(num_reprs):
    edge_indices.append(torch.load(prob_dir + f"edge_index_{i}.pt", weights_only=False))
    edge_reprs.append(torch.load(prob_dir + f"edge_repr_{i}.pt", weights_only=False))
    node_reprs.append(torch.load(prob_dir + f"node_repr_{i}.pt", weights_only=False))

print("Shapes:")
print(f"edge_index:{edge_indices[i].shape}, edge:{edge_reprs[i].shape}, node:{node_reprs[i].shape}")

Shapes:
edge_index:torch.Size([2, 229649]), edge:torch.Size([229649, 256]), node:torch.Size([13757, 256])

tensor([[    0,     0,     0,  ..., 13756, 13756, 13756],
        [    0,     1,     2,  ..., 13747, 13749, 13756]])

In [16]:
y_data = pd.read_pickle("data/probing/y_prob_exp_1.pkl")
y_data

        pred    target
0   6.627124  5.565431
1   6.645761  5.327902
2   6.273721  5.853872
3   6.421379  6.214670
4   6.219614  7.335480
..       ...       ...
95  7.735117  8.958607
96  6.659325  6.121478
97  7.646967  6.856985
98  7.124436  6.357535
99  7.789174  6.990650

[100 rows x 2 columns]

# Hook

In [42]:
from kinodata.model.complex_transformer import ComplexTransformer
from torch import Tensor
from typing import Tuple, Dict
from torch_geometric.data import HeteroData

class ProbingModel(ComplexTransformer):
    def __init__(self, original_model, **kwargs) -> None:
        super().__init__(**kwargs)
        self.original_model = original_model
        self.hidden_states: Dict[str, Tuple[str, Tensor]] = {}

    def forward(self, data: HeteroData) -> Tensor:
        node_store = data[NodeType.Complex]
        node_repr = self.initial_embed_nodes(data)
        edge_index, edge_repr = self.initial_embed_edges(data)

        # Clear previous hidden states
        self.hidden_states.clear()
        
        # Capture the initial representations
        self.hidden_states['initial_node_repr'] = ('initial_node_repr', node_repr.clone())
        self.hidden_states['initial_edge_repr'] = ('initial_edge_repr', edge_repr.clone())
        
        for i, (sparse_attention_block, norm) in enumerate(zip(self.attention_blocks, self.norm_layers)):
            # Run the sparse attention block
            node_repr, edge_repr = sparse_attention_block(node_repr, edge_repr, edge_index)

            # Capture node representation after attention block
            self.hidden_states[f'node_repr_after_block_{i}'] = ('node_repr_after_block', node_repr.clone())
            self.hidden_states[f'edge_repr_after_block_{i}'] = ('edge_repr_after_block', edge_repr.clone())
            
            # Apply normalization
            node_repr = norm(node_repr, node_store.batch)

            # Capture node representation after normalization
            self.hidden_states[f'node_repr_after_norm_{i}'] = ('node_repr_after_norm', node_repr.clone())

        # Aggregate the final node representations
        graph_repr = self.aggr(node_repr, node_store.batch)

        # Capture the final graph representation
        self.hidden_states['final_graph_repr'] = ('final_graph_repr', graph_repr.clone())
        
        return self.out(graph_repr)

In [ ]:
def make_probing_model(model: ComplexTransformer, config: cfg.Config) -> ProbingModel:
    cls = partial(model, config)
    return config.init(cls)